### ISSUE TITLE
Program crashes when trying to download the first video after downloading metadata

### ISSUE THREAD

**Issue by DjShugaA** [jmbannon/ytdl-sub#1035]
Hi
 
Trying to download some videos using my default config file that works on everything else i downloaded.

However when trying to download this particular youtube channel it fails.

[ytdl-sub] The following error occurred for the subscription rick_a:
Traceback (most recent call last):
  File "ytdl_sub\subscriptions\subscription_download.py", line 375, in exception_handling
  File "ytdl_sub\cli\entrypoint.py", line 126, in _download_subscriptions_from_yaml_files
  File "ytdl_sub\subscriptions\subscription_download.py", line 362, in download
  File "ytdl_sub\subscriptions\subscription_download.py", line 306, in _process_subscription
  File "ytdl_sub\downloaders\url\downloader.py", line 529, in download
  File "ytdl_sub\downloaders\url\downloader.py", line 352, in _extract_entry_info_with_retry
  File "ytdl_sub\downloaders\ytdlp.py", line 137, in extract_info_with_retry
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads\\rick_a\\%(id)S.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': 'ffmpeg.exe', 'download_archive': '.ytdl-sub-downloads\\rick_a\\.ytdl-sub-rick_a-download-archive.json-ytdl-archive', 'merge_output_format': 'mp4', 'postprocessors': [{'key': 'FFmpegVideoRemuxer', 'when': 'post_process', 'preferedformat': 'mp4'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'format': "(bv*[ext=mp4][vcodec~='^((he|a)vc|h26[45])']+ba[ext=m4a]) / (bv[ext=mp4]*+ba[ext=m4a]/b)", 'break_on_existing': True, 'break_on_reject': True}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=CbFq4mzykVY'}}
[ytdl-sub]

**Comment by DjShugaA** [comment]
forgot to mention it fails on the first video after downloading meta data

**Comment by DjShugaA** [comment]
I most likely was ip-banned due to downloading too much, it worked when i used a vpn
