### ISSUE TITLE
`enable` option for `chapters` plugin throws error when setting value to `False`

### ISSUE THREAD

**Issue by double128** [jmbannon/ytdl-sub#1071]
As per [plugins.rst](https://github.com/jmbannon/ytdl-sub/blob/88fa55c9dc52db9cc33d76d267ff015b469bebd5/docs/source/config_reference/plugins.rst#chapters), the `chapters` plugin has an `enable` option that can be set to a Boolean value.

I have these custom presets defined in `config.yml`:
``` yml
Youtube Archive:
    preset:
        - "Max 1080p"
    overrides:
        tv_show_directory: "/youtube"
        enable_sponsorblock: True
    chapters:
        enable: "{enable_sponsorblock}"
        sponsorblock_categories:
          - "outro"
          - "selfpromo"
          - "preview"
          - "interaction"
          - "sponsor"
          - "music_offtopic"
          - "intro"
        remove_sponsorblock_categories: "all"
        force_key_frames: False
    output_options:
        maintain_download_archive: True
    ytdl_options:
        cookiefile: "/config/cookie.txt"

Year Seasons:
    preset:
      - "Youtube Archive"
      - "Jellyfin TV Show by Date"

Skip Sponsorblock:
    overrides:
        enable_sponsorblock: False
```

This is what my `subscriptions.yml` file looks like:
``` yml
Year Seasons:
    = Education | Skip Sponsorblock:
        "Internet Comment Etiquette": "https://www.youtube.com/watch?v=GxdxB_HSv_c"
```

When executing a command to download videos with these configurations, an error is thrown:
```
abc@ytdl-sub-gui:~/ytdl-sub-configs$ ytdl-sub sub subscriptions.yaml
[ytdl-sub] Validating subscriptions...
[ytdl-sub] Beginning subscription download for Internet Comment Etiquette
[ytdl-sub:downloader] Downloading metadata for Internet Comment Etiquette: "Kicking Diddy While He's Down"
[ytdl-sub:downloader] Beginning downloads for https://www.youtube.com/watch?v=GxdxB_HSv_c
[ytdl-sub:downloader] Downloading entry 1/1: Internet Comment Etiquette: "Kicking Diddy While He's Down"
[ytdl-sub] The following error occurred for the subscription Internet Comment Etiquette:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 375, in exception_handling
    yield
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/cli/entrypoint.py", line 126, in _download_subscriptions_from_yaml_files
    subscription.download(dry_run=dry_run)
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 362, in download
    return self._process_subscription(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 319, in _process_subscription
    self._process_entry(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 250, in _process_entry
    self._post_process_entry(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 230, in _post_process_entry
    self._move_entry_files_to_output_directory(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 102, in _move_entry_files_to_output_directory
    entry.write_info_json()
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/entries/entry.py", line 178, in write_info_json
    kwargs_dict[_YTDL_SUB_ENTRY_VARIABLES_KWARG_KEY] = self.to_dict()
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/entries/entry.py", line 240, in to_dict
    return self.script.resolve().as_native()
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/script/script.py", line 461, in resolve
    return self._resolve(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/script/script.py", line 404, in _resolve
    resolved[variable] = unresolved[variable].resolve(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/script/types/syntax_tree.py", line 29, in resolve
    self._resolve_argument_type(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/script/types/variable_dependency.py", line 156, in _resolve_argument_type
    return arg.resolve(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/script/types/function.py", line 302, in resolve
    return self.callable(*resolved_arguments)
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/script/functions/error_functions.py", line 14, in throw
    raise UserThrownRuntimeError(error_message)
ytdl_sub.script.utils.exceptions.UserThrownRuntimeError: Plugin variable ytdl_sub_chapters_from_comments has not been created yet
[ytdl-sub] Plugin variable ytdl_sub_chapters_from_comments has not been created yet
[ytdl-sub] Transaction log for Internet Comment Etiquette:
Files created:
----------------------------------------
<SNIP>

[ytdl-sub] Download Summary:
Internet Comment Etiquette     +1 0 0     1 UserThrownRuntimeError
Total: 1                       +1 0 0     1 Error

See `/tmp/ytdl-sub.errors0n1yq_39` for details on errors.
Consider making a GitHub issue including the uploaded log file.
```

The resulting downloaded video is as expected (sections marked by Sponsorblock are not removed), but an error is thrown regardless.

I tested the `enable: False` option with the `nfo_tags` plugin and no error was thrown, so this issue is probably exclusive to the `chapters` plugin. I also get the same outcome if I set `enable: False` directly in `chapters` in my parent preset "Youtube Archive".

---

As a side note, I noticed that the suggestion to look at `/tmp/ytdl-sub.errors0n1yq_39` to see details on the error is actually giving me _less_ details than I would expect:
```
abc@ytdl-sub-gui:~/ytdl-sub-configs$ cat /tmp/ytdl-sub.errors0n1yq_39
[ytdl-sub] Transaction log for Internet Comment Etiquette:
Files created:
----------------------------------------
<Same contents as the SNIP in the previous code block>

[ytdl-sub] Download Summary:
Internet Comment Etiquette     +1 0 0     1 UserThrownRuntimeError
Total: 1                       +1 0 0     1 Error

See `/tmp/ytdl-sub.errors0n1yq_39` for details on errors.
Consider making a GitHub issue including the uploaded log file.
```
I can create a separate ticket for this if this is unexpected behaviour.

**Comment by jmbannon** [comment]
Looks like a legit bug. What I suggest in the meantime is to have your config do the inverse: create a separate `Enable Sponsorblock` preset with the chapters portion
