### ISSUE TITLE
Started getting error 403 when syncing youtube channels since 2024-12-21 15:00 UTC

### ISSUE THREAD

**Issue by christiansacks** [jmbannon/ytdl-sub#1141]
Hi there,

For some reason since 2024-12-21 15:00 ytdl-sub is getting 403 errors when syncing youtube channels. It was working fine for ages, then the last couple of days I noticed no more youtube videos are syncing, checked the logs and saw this;

```
[ytdl-sub] The following error occurred for the subscription History Channel:
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 388, in exception_handling
    yield
  File "/usr/lib/python3.13/site-packages/ytdl_sub/cli/entrypoint.py", line 126, in _download_subscriptions_from_yaml_files
    subscription.download(dry_run=dry_run)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 375, in download
    return self._process_subscription(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        plugins=plugins,
        ^^^^^^^^^^^^^^^^
        downloader=downloader,
        ^^^^^^^^^^^^^^^^^^^^^^
        dry_run=dry_run,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 315, in _process_subscription
    entry = downloader.download(entry)
  File "/usr/lib/python3.13/site-packages/ytdl_sub/downloaders/url/downloader.py", line 532, in download
    download_entry = self._extract_entry_info_with_retry(entry=entry)
  File "/usr/lib/python3.13/site-packages/ytdl_sub/downloaders/url/downloader.py", line 352, in _extract_entry_info_with_retry
    download_entry_dict = YTDLP.extract_info_with_retry(
        ytdl_options_overrides=self.download_ytdl_options(
    ...<8 lines>...
        url=entry.webpage_url,
    )
  File "/usr/lib/python3.13/site-packages/ytdl_sub/downloaders/ytdlp.py", line 137, in extract_info_with_retry
    raise FileNotDownloadedException(
        f"yt-dlp failed to download an entry with these arguments: {error_dict}"
    )
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-working-directory/History Channel/%(id)S.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '.ytdl-sub-working-directory/History Channel/.ytdl-sub-History Channel-download-archive.json-ytdl-archive', 'max_downloads': 5, 'postprocessors': [{'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'break_on_existing': True}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=AVljpgWWnOs'}}
```

Not sure if that is enough to go on, if not I can add more... Interestingly I can download the video using the same url you see in that snipped using yt-dlp outside of ytdl-sub, so I think something happened to ytdl-sub in the last update perhaps?

Any ideas?

**Comment by christiansacks** [comment]
Syncing channels on Odysee.com work fine still though - thought that might be useful to add 😅

**Comment by christiansacks** [comment]
I think it's related to IPv6 - looks like maybe my ISP borked up something in their IPv6 somehow, and I had to use --force-ipv4 for yt-dlp for it to work, but I don't see any way in the yaml to do that for ytdl-sub, how would I pass --force-ipv4 to yt-dlp within the yaml?

**Comment by Jerroder** [comment]
It is [related to IPv6](https://github.com/yt-dlp/yt-dlp/issues/11868), passing `-4` or `--force-ipv4` works for yt-dlp. However I could not find how to add those args from ytdl-sub directly but adding `source_address: '0.0.0.0'` to `ytdl_options` works for me.

```yaml
ytdl_options:
  source_address: '0.0.0.0'
```

**Comment by christiansacks** [comment]
> It is [related to IPv6](https://github.com/yt-dlp/yt-dlp/issues/11868), passing `-4` or `--force-ipv4` works for yt-dlp. However I could not find how to add those args from ytdl-sub directly but adding `source_address: '0.0.0.0'` to `ytdl_options` works for me.
> 
> ```yaml
> ytdl_options:
>   source_address: '0.0.0.0'
> ```

Can you show me exactly how this is supposed to be added please? I've tried under the overrides section directly like;

```
overrides:
    ytdl_options:
        source_address: '0.0.0.0'
```

I've tried under overrides/download/urls, like;
```
overrides:
    download:
        urls:
            ytdl_options:
                source_address: '0.0.0.0'
```
Neither of these worked.

Here is my current yaml file - hopefully you can see where I might have gone wrong and where I might need to set it correctly;
```
~ > head -25 .config/ytdl-sub/tv_show_subscriptions.yaml
__preset__:
  overrides:
    tv_show_directory: "/mnt/plex/ytdl-sub"  # Root folder of all ytdl-sub TV Shows

    #download:
    #    urls:
    #        ytdl_options:
    #            cookiefile: "/home/christian/Videos/cookies.txt"
    #            force_ipv4: True
    #            user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0"
    #            source_address: '0.0.0.0'

    # For 'Only Recent' preset, only keep vids within this range and limit
    only_recent_date_range: "1months"
    only_recent_max_files: 5

    check_formats:
        ytdl_options:
            check_formats: True

    #ytdl_options:
    #    cookiefile: "/home/christian/Videos/cookies.txt"
    #    force_ipv4: True
    #    user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0"
    #    source_address: '0.0.0.0'
```

I've commented both sections out for now as neither seemed to work for me.

**Comment by christiansacks** [comment]
Aha! I think I just figured out where to put it;
```
~ > head -5 .config/ytdl-sub/tv_show_subscriptions.yaml
__preset__:
  
  ytdl_options:
    source_address: '0.0.0.0'
```

This seems to be working 🤞🏻

**Comment by ddubnyk** [comment]
I am getting this no matter what video or option I try for the last several days.  Although I'm wondering if this is more of a yt-dlp issue since my devices are experiencing this with Newpipe and Grayjay as well.  Anyways, here is the log:

`    preset:
    - _jellyfin_tv_show
    - _tv_show_by_date
    - _season_by_year
    - jellyfin_tv_show_by_date
    - season_by_year__episode_by_month_day
    - sponsorblock
    - tv_show
    - only_recent_videos
    video_tags:
      contentRating: '{episode_content_rating}'
      date: '{episode_date_standardized}'
      episode_id: '{episode_number}'
      genre: '{tv_show_genre}'
      show: '{tv_show_name}'
      synopsis: '{episode_plot}'
      title: '{episode_title}'
      year: '{episode_year}'
    ytdl_options:
      break_on_existing: true
      break_on_reject: true
      format: bv[width<=1920]+ba
      source_address: 0.0.0.0

[ytdl-sub:ytdl-options] Setting match-filters: 
 - !is_live & !is_upcoming & !post_live
[ytdl-sub:ytdl-options] Setting breaking-match-filters: 
 - upload_date >= 20241216
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads/Formafist Live/%(id)S.%(ext)s', 'writethumbnail': False, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '.ytdl-sub-downloads/Formafist Live/.ytdl-sub-Formafist Live-download-archive.json-ytdl-archive', 'match_filter': yt_dlp.utils.match_filter_func(['!is_live & !is_upcoming & !post_live'], ['upload_date >= 20241216']), 'break_on_existing': True, 'format': 'bv[width<=1920]+ba', 'source_address': '0.0.0.0', 'break_on_reject': True, 'skip_download': True, 'writeinfojson': True, 'extract_flat': 'discard'}
[ytdl-sub:yt-dlp] [youtube:tab] Extracting URL: https://www.youtube.com/user/formafist/streams
[ytdl-sub:yt-dlp] [youtube:tab] formafist/streams: Downloading webpage
[ytdl-sub:yt-dlp] [download] Downloading playlist: FORMAFIST (8pm PST) - Live
[ytdl-sub:yt-dlp] [info] Writing playlist metadata as JSON to: .ytdl-sub-downloads/Formafist Live/UCuR89X5z_mmglTJZudW3tzA.info.json
[ytdl-sub:yt-dlp] [youtube:tab] Playlist FORMAFIST (8pm PST) - Live: Downloading 2 items
[ytdl-sub:yt-dlp] [download] Downloading item 1 of 2
[ytdl-sub:yt-dlp] [youtube] Extracting URL: https://www.youtube.com/watch?v=BFiIKvopPRM
[ytdl-sub:yt-dlp] [youtube] BFiIKvopPRM: Downloading webpage
[ytdl-sub:downloader] Downloading metadata for FORMAFIST (8pm PST) - Live
[ytdl-sub:yt-dlp] [youtube] BFiIKvopPRM: Downloading ios player API JSON
[ytdl-sub:yt-dlp] [youtube] BFiIKvopPRM: Downloading mweb player API JSON
[ytdl-sub:yt-dlp] [youtube] BFiIKvopPRM: Downloading m3u8 information
[ytdl-sub:yt-dlp] [info] BFiIKvopPRM: Downloading 1 format(s): 136+251
[ytdl-sub:yt-dlp] [info] Writing video metadata as JSON to: .ytdl-sub-downloads/Formafist Live/BFiIKvopPRM.info.json
[ytdl-sub:yt-dlp] [download] GJLRfx6u96w: FORMAFIST LIVE FROM CANADA - 8pm PST Everyday (Justin Trudeau is a big quitter)) has already been recorded in the archive
[ytdl-sub:yt-dlp-downloader] ExistingVideoReached, stopping additional downloads. (Can be disable by setting `ytdl_options.break_on_existing` to False).
[ytdl-sub:yt-dlp-downloader] Attempting to get parent metadata from URL https://www.youtube.com/@formafist
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads/Formafist Live/%(id)S.%(ext)s', 'writethumbnail': False, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '.ytdl-sub-downloads/Formafist Live/.ytdl-sub-Formafist Live-download-archive.json-ytdl-archive', 'match_filter': yt_dlp.utils.match_filter_func(['!is_live & !is_upcoming & !post_live'], ['upload_date >= 20241216']), 'break_on_existing': True, 'format': 'bv[width<=1920]+ba', 'source_address': '0.0.0.0', 'break_on_reject': True, 'skip_download': True, 'writeinfojson': True, 'extract_flat': 'discard', 'playlist_items': '0:0'}
[ytdl-sub:yt-dlp] [youtube:tab] Extracting URL: https://www.youtube.com/@formafist
[ytdl-sub:yt-dlp] [youtube:tab] @formafist: Downloading webpage
[ytdl-sub:yt-dlp] [youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[ytdl-sub:yt-dlp] [youtube:tab] @formafist/streams: Downloading webpage
[ytdl-sub:yt-dlp] [youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUuR89X5z_mmglTJZudW3tzA
[ytdl-sub:yt-dlp] [download] Downloading playlist: FORMAFIST (8pm PST)
[ytdl-sub:yt-dlp] [info] Writing playlist metadata as JSON to: .ytdl-sub-downloads/Formafist Live/@formafist.info.json
[ytdl-sub:yt-dlp] [youtube:tab] Playlist FORMAFIST (8pm PST): Downloading 0 items of 2
[ytdl-sub:yt-dlp] [info] Writing updated playlist metadata as JSON to: .ytdl-sub-downloads/Formafist Live/@formafist.info.json
[ytdl-sub:yt-dlp] [download] Finished downloading playlist: FORMAFIST (8pm PST)
[ytdl-sub:yt-dlp-downloader] Adding parent metadata with ids [@formafist, @formafist]
[ytdl-sub:downloader] Beginning downloads for https://www.youtube.com/user/formafist/streams
[ytdl-sub:downloader] Downloading entry 1/1: Canadian Real Estate! (and Other Less Important News) - 8pm PST Everyday
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads/Formafist Live/%(id)S.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '.ytdl-sub-downloads/Formafist Live/.ytdl-sub-Formafist Live-download-archive.json-ytdl-archive', 'postprocessors': [{'key': 'SponsorBlock', 'when': 'pre_process', 'categories': ['sponsor']}, {'key': 'ModifyChapters'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'ModifyChapters', 'force_keyframes': False, 'remove_sponsor_segments': ['sponsor']}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'break_on_existing': True, 'format': 'bv[width<=1920]+ba', 'source_address': '0.0.0.0', 'break_on_reject': True}
[ytdl-sub:yt-dlp] [youtube] Extracting URL: https://www.youtube.com/watch?v=BFiIKvopPRM
[ytdl-sub:yt-dlp] [youtube] BFiIKvopPRM: Downloading webpage
[ytdl-sub:yt-dlp] [youtube] BFiIKvopPRM: Downloading ios player API JSON
[ytdl-sub:yt-dlp] [youtube] BFiIKvopPRM: Downloading mweb player API JSON
[ytdl-sub:yt-dlp] [youtube] BFiIKvopPRM: Downloading m3u8 information
[ytdl-sub:yt-dlp] [SponsorBlock] Fetching SponsorBlock segments
[ytdl-sub:yt-dlp] [SponsorBlock] No matching segments were found in the SponsorBlock database
[ytdl-sub:yt-dlp] [info] BFiIKvopPRM: Downloading 1 format(s): 136+251
[ytdl-sub:yt-dlp] [info] Downloading video thumbnail 46 ...
[ytdl-sub:yt-dlp] [info] Writing video thumbnail 46 to: .ytdl-sub-downloads/Formafist Live/BFiIKvopPRM.webp
[ytdl-sub:yt-dlp] ERROR: unable to download video data: HTTP Error 403: Forbidden
[ytdl-sub:yt-dlp-downloader] Failed to download entry. Retrying 1 / 5`

**Comment by jmbannon** [comment]
Make sure you are on the latest version of ytdl-sub. Realized the GUI image was lagging behind a few days, but is fixed now.

**Comment by jmbannon** [comment]
@christiansacks try this: https://github.com/jmbannon/ytdl-sub/issues/1131#issuecomment-2542530554

**Comment by christiansacks** [comment]
> @christiansacks try this: https://github.com/jmbannon/ytdl-sub/issues/1131#issuecomment-2542530554

Ooh nice, will give it a try and let you know if it didn't work. 

Thank you!

**Comment by jmbannon** [comment]
Forgot to mention 403s are typically due to throttle. Look into adding [throttle protection](https://ytdl-sub.readthedocs.io/en/latest/config_reference/plugins.html#throttle-protection) -- very soon I will bake this into the prebuilt presets.

Going to close but still happy to help

**Comment by christiansacks** [comment]
With the latest update to yt-dlp this now happens in ytdl-sub
```
[ytdl-sub:yt-dlp] WARNING: [youtube:tab] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[ytdl-sub:yt-dlp] WARNING: [youtube:tab] Incomplete yt initial data received; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U. Giving up after 3 retries
[ytdl-sub:yt-dlp] ERROR: [youtube:tab] @ChannelName: Playlists that require authentication may not extract correctly without a successful webpage download. If you are not downloading private content, or your cookies are only for the first account and channel, pass "--extractor-args youtubetab:skip=authcheck" to skip this check
```

**Comment by axsuul** [comment]
> > [@christiansacks](https://github.com/christiansacks) try this: [#1131 (comment)](https://github.com/jmbannon/ytdl-sub/issues/1131#issuecomment-2542530554)
> 
> Ooh nice, will give it a try and let you know if it didn't work.
> 
> Thank you!
> 
> Update: I tried it and it still shows the errors.
> 
> I'm also seeing a lot of "ERROR: [YouTube] someid: Video unavailable. This content isn't available, try again later.". I don't think I saw it before forcing the SSL cert dir. Will investigate.

I'm also getting this error now. Any suggestions?

**Comment by jmbannon** [comment]
A common fix is to remove cookiefile, often times it becomes expired and causes weird errors.
