### ISSUE TITLE
Converting youtube video to mp3 errors

### ISSUE THREAD

**Issue by fluffystranger** [jmbannon/ytdl-sub#175]
**[Usecase]**
I am attempting to grab **only** the audio source from youtube videos and I am a tad bit confused by how extracting it from videos should be configured, in order to work properly.

I've configured the following youtube preset in my **config.yaml**:
```
  youtube_song:
    youtube:
      download_strategy: "video"

    ytdl_options:
      ignoreerrors: True
      format: "bestvideo[ext=mp4][width<=1920][height<=1080]+bestaudio[ext=mp3]"
      postprocessors:
        # Convert the videos to mp3 format
        - key: "FFmpegExtractAudio"
          when: "post_process"
          preferredcodec: "mp3"
          preferredquality: "128"

    output_options:
      output_directory: "/music/"
      file_name: "{video_path}"
      thumbnail_name: "{video_path}.{thumbnail_ext}"

    overrides:
      video_name: "{upload_date_standardized}.{title_sanitized}.mp3"
      video_path: "{video_name_sanitized}"
```
and I'm using the following, in order to extract an audio source from the video soruce:
```
ytdl-sub dl --preset "youtube_song" --youtube.video_url "https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab"
```

The log points out to the fact that move operation fails, but the process seems to attempt to mv the original file, rather than the extracted audio file, to the output_directory.
That is not the use case I am interested in, and as the log points out, the original file is removed after the post-processing phase.
Log:
```
[ytdl-sub:downloader] ytdl_options: {'ignoreerrors': True, 'break_on_existing': True, 'format': 'bestvideo[ext=mp4][width<=1920][height<=1080]+bestaudio[ext=mp3] / best[ext=mp4] / best', 'postprocessors': [{'key': 'FFmpegExtractAudio', 'when': 'post_process', 'preferredcodec': 'mp3', 'preferredquality': '320'}], 'writethumbnail': True, 'outtmpl': '/tmp/ytdl-sub-downloads/cli-dl-5a0219d3/%(id)s.%(ext)s'}
[ytdl-sub:yt-dlp] [youtube] dQw4w9WgXcQ: Downloading webpage
[ytdl-sub:yt-dlp] [youtube] dQw4w9WgXcQ: Downloading android player API JSON
[ytdl-sub:yt-dlp] [info] dQw4w9WgXcQ: Downloading 1 format(s): 22
[ytdl-sub:yt-dlp] [info] Downloading video thumbnail 41 ...
[ytdl-sub:yt-dlp] [info] Writing video thumbnail 41 to: /tmp/ytdl-sub-downloads/cli-dl-5a0219d3/dQw4w9WgXcQ.webp
[ytdl-sub:yt-dlp] [download] Destination: /tmp/ytdl-sub-downloads/cli-dl-5a0219d3/dQw4w9WgXcQ.mp4
[download]   0.0% of 64.68MiB at  419.56KiB/s ETA 02:43
[download]   0.0% of 64.68MiB at  488.01KiB/s ETA 02:17
[download]   0.0% of 64.68MiB at  300.63KiB/s ETA 03:41
[download]   0.0% of 64.68MiB at  563.88KiB/s ETA 01:57
[download]   0.0% of 64.68MiB at  824.90KiB/s ETA 01:20
[download]   0.1% of 64.68MiB at    1.25MiB/s ETA 00:51
[download]   0.2% of 64.68MiB at    1.65MiB/s ETA 00:39
[download]   0.4% of 64.68MiB at    2.33MiB/s ETA 00:27
[download]   0.8% of 64.68MiB at    3.27MiB/s ETA 00:19
[download]   1.5% of 64.68MiB at    3.84MiB/s ETA 00:16
[download]   3.1% of 64.68MiB at    4.32MiB/s ETA 00:14
[download]   6.2% of 64.68MiB at    4.98MiB/s ETA 00:12
[download]  12.4% of 64.68MiB at    5.25MiB/s ETA 00:10
[download]  18.6% of 64.68MiB at    5.79MiB/s ETA 00:09
[download]  24.7% of 64.68MiB at    6.09MiB/s ETA 00:07
[download]  30.9% of 64.68MiB at    6.26MiB/s ETA 00:07
[download]  37.1% of 64.68MiB at    6.44MiB/s ETA 00:06
[download]  43.3% of 64.68MiB at    6.58MiB/s ETA 00:05
[download]  49.5% of 64.68MiB at    6.71MiB/s ETA 00:04
[download]  55.7% of 64.68MiB at    6.56MiB/s ETA 00:04
[download]  61.8% of 64.68MiB at    6.42MiB/s ETA 00:03
[download]  68.0% of 64.68MiB at    6.43MiB/s ETA 00:03
[download]  74.2% of 64.68MiB at    6.46MiB/s ETA 00:02
[download]  80.4% of 64.68MiB at    6.54MiB/s ETA 00:01
[download]  86.6% of 64.68MiB at    6.60MiB/s ETA 00:01
[download]  92.8% of 64.68MiB at    6.67MiB/s ETA 00:00
[download]  99.0% of 64.68MiB at    6.72MiB/s ETA 00:00
[download] 100.0% of 64.68MiB at    6.75MiB/s ETA 00:00
[download] 100% of 64.68MiB in 00:12
[ytdl-sub:yt-dlp] [ExtractAudio] Destination: /tmp/ytdl-sub-downloads/cli-dl-5a0219d3/dQw4w9WgXcQ.mp3
[ytdl-sub:yt-dlp] Deleting original file /tmp/ytdl-sub-downloads/cli-dl-5a0219d3/dQw4w9WgXcQ.mp4 (pass -k to keep)
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Cross-device link: '/tmp/ytdl-sub-downloads/cli-dl-5a0219d3/dQw4w9WgXcQ.mp4' -> '/music/2009-10-25.Rick Astley - Never Gonna Give You Up (Official Music Video).mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 28, in main
    _main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 19, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 111, in main
    _download_subscription_from_cli(config=config, args=args, extra_args=extra_args)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 89, in _download_subscription_from_cli
    return subscription, subscription.download(dry_run=args.dry_run)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription.py", line 307, in download
    self._move_entry_files_to_output_directory(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription.py", line 174, in _move_entry_files_to_output_directory
    self._enhanced_download_archive.save_file_to_output_directory(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/ytdl_additions/enhanced_download_archive.py", line 579, in save_file_to_output_directory
    self._file_handler.move_file_to_output_directory(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/utils/file_handler.py", line 246, in move_file_to_output_directory
    self.move(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/utils/file_handler.py", line 209, in move
    shutil.move(src=src_file_path, dst=dst_file_path)
  File "/usr/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ytdl-sub-downloads/cli-dl-5a0219d3/dQw4w9WgXcQ.mp4'
```

Am I missing something obvious in the configuration, or is my approach here somewhat incorrect/unsupported?
My apologies if this was documented somewhere here or in yt-dlp, and I have obliviously missed it.

**Comment by jmbannon** [comment]
Hi @fluffystranger , your config looks good - this looks like an actual bug. In the backend we're using the `ext` field from yt-dlp's info json to reference the filepath. It's probably set to mp4 when in actuality it's mp3. I will get this fixed soon

**Comment by jmbannon** [comment]
The PR linked should support extracting audio from videos, playlists, and channels. One of my personal use cases is to also be able to split a video by chapters, and make each chapter its own audio file. Will work on that next

**Comment by jmbannon** [comment]
Merged :tada: 
@fluffystranger Here are the docs on the audio extract fields: https://ytdl-sub.readthedocs.io/en/latest/config.html#audio-extract

**Comment by fluffystranger** [comment]
awesome, thanks for the update!
