### ISSUE TITLE
Address not available

### ISSUE THREAD

**Issue by ohare93** [jmbannon/ytdl-sub#212]
Strange error occurs after downloading the first entry in Subscriptions list. Even if the downloads are already complete. Some address is unavailable, but it does not say which.

```
[ytdl-sub] Beginning subscription download for e-r
[ytdl-sub:downloader] ytdl_options: {'ignoreerrors': True, 'break_on_existing': True, 'break_on_reject': True, 'outtmpl': '/tmp/ytdl-sub-downloads/e-r/%(id)s.%(ext)s', 'download_archive': '/tmp/ytdl-sub-downloads/e-r/.ytdl-subscribe-e-r-download-archive.txt', 'writethumbnail': False, 'daterange': <yt_dlp.utils.DateRange object at 0x1548f112eb00>, 'writesubtitles': True, 'postprocessors': [{'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': True}, {'key': 'FFmpegSubtitlesConvertor', 'format': 'srt'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': True}, {'key': 'FFmpegSubtitlesConvertor', 'format': 'srt'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'writeautomaticsub': True, 'subtitleslangs': ['en', 'en'], 'writeinfojson': True, 'skip_download': True}
[ytdl-sub:yt-dlp] [youtube:tab] ERofthesemicolon: Downloading webpage
[ytdl-sub:yt-dlp] [youtube:tab] A channel/user page was given. All the channel's videos will be downloaded. To download only the videos in the home page, add a "/featured" to the URL
[ytdl-sub:yt-dlp] [download] Downloading playlist: E;R - Videos
[ytdl-sub:yt-dlp] [info] Writing playlist metadata as JSON to: /tmp/ytdl-sub-downloads/e-r/UC4BZtFgtCuHUt0p8J-XENiA.info.json
[ytdl-sub:yt-dlp] [youtube:tab] Playlist E;R - Videos: Downloading 1 videos
[ytdl-sub:yt-dlp] [download] The Legend of Whorra: Book 3 (Part 1) has already been recorded in the archive
[ytdl-sub:downloader] ExistingVideoReached, stopping additional downloads
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Address not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 28, in main
    _main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 19, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 106, in main
    transaction_logs = _download_subscriptions_from_yaml_files(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 46, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=args.dry_run)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 268, in download
    downloader.post_download()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/youtube/channel.py", line 258, in post_download
    self._download_thumbnail(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/youtube/channel.py", line 246, in _download_thumbnail
    convert_url_thumbnail(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/utils/thumbnail.py", line 46, in convert_url_thumbnail
    with urlopen(thumbnail_url) as file:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Address not available>
[ytdl-sub] Please upload the error log file '/tmp/ytdl-sub.j35ju1_p' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!

```

<details>
  <summary>Config</summary>

  ```
configuration:
  working_directory: '/tmp/ytdl-sub-downloads'
  # umask: "002"

presets:

  ###############################################################################
  # Single video as an episode
  yt_episode:
    output_options:
      output_directory: "{youtube_tv_shows_directory}/{show_name_sanitized}"
      file_name: "{episode_file_path}.{ext}"
      thumbnail_name: "{episode_file_path}-thumb.jpg"
      info_json_name: "{episode_file_path}.{info_json_ext}"
      maintain_download_archive: True

    nfo_tags:
      nfo_name: "{episode_file_path}.nfo"
      nfo_root: "episodedetails"
      kodi_safe: True
      tags:
        title: "{episode_title}"
        season: "{season}"
        episode: "{episode}"
        year: "{upload_year}"
        plot: "{description}"
        aired: "{upload_date_standardized}"
        genre: "Unset"

    chapters:
      embed_chapters: True

    subtitles:
      subtitles_name: "{episode_file_path}.{lang}.{subtitles_ext}"
      embed_subtitles: True
      languages: "en"
      allow_auto_generated_subtitles: True
  
    overrides:
      youtube_tv_shows_directory: "/tv_shows"
      season: "{upload_year}"
      episode: "{upload_month_reversed}{upload_day_reversed_padded}"
      episode_padded: "{upload_month_reversed_padded}{upload_day_reversed_padded}"
      episode_title: "{upload_date_standardized} - {title}"
      episode_file_name: "s{season}.e{episode_padded} - {episode_title}"
      episode_file_path: "Season {season}/{episode_file_name}"


  ###############################################################################
  # Create a TV show from a youtube playlist or channel
  yt_show:
    preset: "yt_episode"
    output_directory_nfo_tags:
      nfo_name: "tvshow.nfo"
      nfo_root: "tvshow"
      kodi_safe: True
      tags:
        title: "{show_name}"


  ###############################################################################
  # Entire channel as a TV show
  yt_channel:
    preset: "yt_show"
    youtube:
      download_strategy: "channel"
      channel_avatar_path: "poster.jpg"
      channel_banner_path: "fanart.jpg"

  ###############################################################################
  # Playlist as a TV show
  yt_playlist:
    preset: "yt_show"
    youtube:
      download_strategy: "playlist"
    ytdl_options:
      break_on_reject: True

  ###############################################################################
  # Only store recent videos in the last {time_to_live} timespan.
  # Defaults to 2 months
  only_recent:
    output_options:
      keep_files_after: "today-{time_to_live}"
    date_range:
      after: "today-{time_to_live}"
    overrides:
      time_to_live: "1months"

  ###############################################################################
  # For channels/playlists/etc with known sponsor content.
  # Wait 2 days after upload for sponsorblock submissions, then cut it out.
  sponsor_block:
    date_range:
      before: "today-2days"

    chapters:
      sponsorblock_categories:
        - "outro"
        - "selfpromo"
        - "preview"
        - "interaction"
        - "sponsor"
        - "music_offtopic"
        - "intro"
      remove_sponsorblock_categories: "all"
      force_key_frames: True

```
</details>

<details>
  <summary>Subscriptions</summary>

  ```
 
e-r:
  preset:
    - "yt_channel"
    - "only_recent"
    # - "sponsor_block"
  youtube:
    channel_url: "https://www.youtube.com/c/ERofthesemicolon"
  overrides:
    show_name: "E;R"
    


charles_dowding:
  preset:
    - "yt_channel"
    - "only_recent"
    # - "sponsor_block"
  youtube:
    channel_url: "https://www.youtube.com/c/CharlesDowding1nodig"
  overrides:
    show_name: "Charles Dowding"
    
matt_christiansen:
  preset:
    - "yt_channel"
    - "only_recent"
    # - "sponsor_block"
  youtube:
    channel_url: "https://www.youtube.com/c/skagg3"
  overrides:
    show_name: "Matt Christiansen"

```

</details>

**Comment by jmbannon** [comment]
Thanks for the report! It fails trying to download the channel's thumbnail/banner. Closing since this is a duplicate issue: https://github.com/jmbannon/ytdl-sub/issues/214

**Comment by ohare93** [comment]
Worth noting, how my issue is different than the other mentioned one: the first channels' videos download, then the error occurs, then no further channel's videos download. So this issue is more blocking than it appears.

**Comment by jmbannon** [comment]
Right - any error stops all subsequent ytdl-sub downloads. This is my top-priority bug, should get a fix in soon
