### ISSUE TITLE
playlist error when downloading

### ISSUE THREAD

**Issue by Code-Slave** [jmbannon/ytdl-sub#217]
Throws this

[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 28, in main
    _main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 19, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 106, in main
    transaction_logs = _download_subscriptions_from_yaml_files(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 46, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=args.dry_run)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 254, in download
    for entry in downloader.download():
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/youtube/playlist.py", line 97, in download
    playlist = self._filter_entry_dicts(entry_dicts, extractor="youtube:tab")[0]
IndexError: list index out of range

I just upgraded to latest. worked 3 days ago.

**Comment by Code-Slave** [comment]
NVM marked private. leaving for reference
