### ISSUE TITLE
Filename too long

### ISSUE THREAD

**Issue by sbhal** [jmbannon/ytdl-sub#222]
```
OSError: [Errno 36] Filename too long: '/tmp/ytdl-sub-downloads/bbc_hindi_channel/Season 2022⧸s2022.e0425 - 2022-09-06 - Gay Life : समलैंगिक होने पर ज़िंदगी में क्या चुनौतियां आती हैं और उनसे कैसे निपटा जाता है? (BBC).nfo'
```

Traceback:
```
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 28, in main
    _main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 19, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 106, in main
    transaction_logs = _download_subscriptions_from_yaml_files(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 46, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=args.dry_run)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 264, in download
    self._process_entry(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 184, in _process_entry
    self._post_process_entry(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 162, in _post_process_entry
    optional_plugin_entry_metadata = plugin.post_process_entry(entry)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/plugins/nfo_tags.py", line 271, in post_process_entry
    self._create_nfo(entry=entry)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/plugins/nfo_tags.py", line 157, in _create_nfo
    with open(nfo_file_path, "wb") as nfo_file:
OSError: [Errno 36] Filename too long: '/tmp/ytdl-sub-downloads/bbc_hindi_channel/Season 2022⧸s2022.e0425 - 2022-09-06 - Gay Life : समलैंगिक होने पर ज़िंदगी में क्या चुनौतियां आती हैं और उनसे कैसे निपटा जाता है? (BBC).nfo'
```

**Comment by sbhal** [comment]
Preset used
```
  yt_episode:
    youtube:
      download_strategy: "video"
    output_options:
      output_directory: "{youtube_tv_shows_directory}/{tv_show_name_sanitized}"
      file_name: "{episode_file_path}.{ext}"
      thumbnail_name: "{episode_file_path}-thumb.jpg"
      info_json_name: "{episode_file_path}.{info_json_ext}"
      maintain_download_archive: True

    nfo_tags:
      nfo_name: "{episode_file_path_sanitized}.nfo"
      nfo_root: "episodedetails"
      kodi_safe: True
      tags:
        title: "{episode_title}"
        season: "{season}"
        episode: "{episode}"
        year: "{upload_year}"
        plot: "{description}"
        aired: "{upload_date_standardized}"
        genre: "Unset"

    chapters:
      embed_chapters: True
  
    overrides:
      youtube_tv_shows_directory: "/myvids/youtube"
      tv_show_name: "OVERRIDE IN SUBSCRIPTION"
      season: "{upload_year}"
      episode: "{upload_month_reversed}{upload_day_reversed_padded}"
      episode_padded: "{upload_month_reversed_padded}{upload_day_reversed_padded}"
      episode_title: "{upload_date_standardized} - {title}"
      episode_file_name: "s{season}.e{episode_padded} - {episode_title}"
      episode_file_path: "Season {season}/{episode_file_name}"
```

**Comment by sbhal** [comment]
Maybe a wrapper around https://github.com/yt-dlp/yt-dlp/blob/17ffed184237b3686212cc73290e5cdd0f6f20ca/yt_dlp/utils.py#L647 could help here.

**Comment by jmbannon** [comment]
Use `title_sanitized` instead of `title` in the filename - it will call that function. Let me know if that fixes the issue.

Normally you could just use `episode_title_sanitized`, but there currently is a bug that does not sanitize it after it resolves: https://github.com/jmbannon/ytdl-sub/issues/210

**Comment by jmbannon** [comment]
Looking further into this, I do not think sanitizing it will fix the issue. It needs to be truncated somehow. The long string of unicode characters quickly consume the 255 byte limit.
