### ISSUE TITLE
Error when downloading

### ISSUE THREAD

**Issue by Vorror** [jmbannon/ytdl-sub#377]
Received this python error when downloading
```
[ytdl-sub:downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '/temp/staging_downloads/reinelex_mix/%(id)s.%(ext)s', 'writethumbnail': True, 'download_archive': '/temp/staging_downloads/reinelex_mix/.ytdl-subscribe-reinelex_mix-download-archive.txt', 'postprocessors': [{'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'ModifyChapters', 'force_keyframes': False, 'remove_chapters_patterns': [re.compile('(?i)^Repeats?$', re.IGNORECASE)]}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'FFmpegExtractAudio', 'when': 'post_process', 'preferredcodec': 'm4a', 'preferredquality': 0}], 'format': 'bestaudio[ext=webm]', 'concurrent_fragments': 4}
[ytdl-sub:yt-dlp] [Youtube] Bu3kAbpi5jo: has already been recorded in the archive
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 28, in main
    _main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 19, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 174, in main
    transaction_logs = _download_subscriptions_from_yaml_files(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 60, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=args.dry_run)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 257, in download
    for entry in downloader.download():
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 581, in download
    for entry in self._download(parents=parents, orphans=orphan_entries):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 559, in _download
    for entry_child in self._download_parent_entry(parent=parent):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 497, in _download_parent_entry
    for entry_child in self._download_entries(parent.entry_children()):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 493, in _download_entries
    yield self._download_entry(entry)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 459, in _download_entry
    REQUESTED_SUBTITLES: download_entry.kwargs_get(REQUESTED_SUBTITLES),
  File "/usr/lib/python3.10/site-packages/ytdl_sub/entries/base_entry.py", line 223, in kwargs_get
    if not self.kwargs_contains(key) or self.kwargs(key) is None:
  File "/usr/lib/python3.10/site-packages/ytdl_sub/entries/base_entry.py", line 206, in kwargs_contains
    return key in self._kwargs
TypeError: argument of type 'NoneType' is not iterable
```

Attached Logs/config: 

[Archive.zip](https://github.com/jmbannon/ytdl-sub/files/10115527/Archive.zip)

**Comment by Vorror** [comment]
That sounds about right. Deleting my download archive for that subscription fixed the issue. Luckily, it had only downloaded about 5 files or so.  Next time, I'll probably just manually remove that entry.

**Comment by jmbannon** [comment]
Nice. And thanks btw for the detailed issues!

**Comment by jmbannon** [comment]
Did some tests, and found that if it's downloaded in the archive, it will not download the info.json file. Therefore, I think you had leftover info.json files in the working directory from a previous download.

Then on a successive download, it used this old info.json file thinking it was downloaded metadata, tried to download, but was in the archive so it returned None, then error'd.

I think https://github.com/jmbannon/ytdl-sub/pull/379 should fix it (was merged 1 day after this issue). So going to close this out
