### ISSUE TITLE
Splitting albums by chapters eats too much disk

### ISSUE THREAD

**Issue by jmbannon** [jmbannon/ytdl-sub#378]
```
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 28, in main
    _main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 19, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 172, in main
    transaction_logs = _download_subscriptions_from_yaml_files(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 59, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=args.dry_run)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 257, in download
    for entry in downloader.download():
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 560, in download
    for entry in self._download(parents=parents, orphans=orphan_entries):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 545, in _download
    for entry_child in self._download_parent_entry(parent=parent):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 478, in _download_parent_entry
    for entry_child in self._download_entries(parent.entry_children()):
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 474, in _download_entries
    yield self._download_entry(entry)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 444, in _download_entry
    download_entry = self._extract_entry_info_with_retry(entry=entry)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 432, in _extract_entry_info_with_retry
    download_entry_dict = self.extract_info_with_retry(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 258, in extract_info_with_retry
    entry_dict = self.extract_info(
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 220, in extract_info
    with self.ytdl_downloader(ytdl_options_overrides) as ytdl_downloader:
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 187, in ytdl_downloader
    with ytdl.YoutubeDL(ytdl_options_overrides) as ytdl_downloader:
  File "/usr/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 911, in __exit__
    self.cookiejar.save(ignore_discard=True, ignore_expires=True)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 1614, in save
    with self.open(filename, write=True) as f:
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/usr/lib/python3.10/site-packages/yt_dlp/utils.py", line 1569, in open
    with open(file, 'w' if write else 'r', encoding='utf-8') as f:
OSError: [Errno 28] No space left on device
```

**Comment by jmbannon** [comment]
Ran for ~3 days, splitting 400+ albums. My guess is we don't delete the original file after splitting

**Comment by Vorror** [comment]
I've actually hit this issue too. My server only had 64GB of onboard storage, so the temp directory, which was located on the OS Disk got full. The simple fix was to move the temp directory to another drive. I never opened a ticket since it had a straightforward workaround.
