### ISSUE TITLE
youtube channel crashes app

### ISSUE THREAD

**Issue by binarygeek119** [jmbannon/ytdl-sub#398]
it happen with this channel if i remove it, it works.

`[ytdl-sub:downloader] Downloading entry 1/77: Stop Saying Amperage!
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 28, in main
_main()
File "/usr/lib/python3.10/site-packages/ytdl_sub/main.py", line 19, in _main
ytdl_sub.cli.main.main()
File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 174, in main
transaction_logs = _download_subscriptions_from_yaml_files(config=config, args=args)
File "/usr/lib/python3.10/site-packages/ytdl_sub/cli/main.py", line 60, in _download_subscriptions_from_yaml_files
transaction_log = subscription.download(dry_run=args.dry_run)
File "/usr/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 288, in download
for entry in downloader.download():
File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 581, in download
for entry in self._download(parents=parents, orphans=orphan_entries):
File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 559, in _download
for entry_child in self._download_parent_entry(parent=parent):
File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 502, in _download_parent_entry
for entry_child in self._download_parent_entry(parent=parent_child):
File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 497, in _download_parent_entry
for entry_child in self._download_entries(parent.entry_children()):
File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 493, in _download_entries
yield self._download_entry(entry)
File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 449, in _download_entry
download_entry = self._extract_entry_info_with_retry(entry=entry)
File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 438, in _extract_entry_info_with_retry
download_entry_dict = self.extract_info_with_retry(
File "/usr/lib/python3.10/site-packages/ytdl_sub/downloaders/downloader.py", line 298, in extract_info_with_retry
raise FileNotDownloadedException(
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '/tmp/ytdl-sub-downloads/bytesized/%(id)s.%(ext)s', 'writethumbnail': True, 'download_archive': '/tmp/ytdl-sub-downloads/bytesized/.ytdl-sub-bytesized-download-archive.txt', 'writesubtitles': True, 'postprocessors': [{'key': 'FFmpegSubtitlesConvertor', 'format': 'srt'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'writeautomaticsub': True, 'subtitleslangs': ['en'], 'cookiefile': '/config/cookies.txt', 'break_on_existing': True}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=OcjabV3pT7M'}}
[ytdl-sub] Please upload the error log file '/tmp/ytdl-sub.or_ymrb9' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!`

`bytesized:
  preset:
    - TV
    - jellyfin_tv_show_by_date
    - season_by_year__episode_by_month_day
  overrides:
    tv_show_name: byte sized engineering
    url: https://www.youtube.com/@bytesized
    tv_show_directory: /tv_shows`

**Comment by orthanc42** [comment]
is your subscription info missing quotations around the tv_show_name and url?

**Comment by binarygeek119** [comment]
thats it thank you
