### ISSUE TITLE
Crash when downloading

### ISSUE THREAD

**Issue by DaveAlton** [jmbannon/ytdl-sub#436]
I'm unsure why, but it's crashing when I try to download anything. Have I missed an installation step?

```
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/Applications/ytdl-sub/src/ytdl_sub/main.py", line 28, in main
    _main()
  File "/Applications/ytdl-sub/src/ytdl_sub/main.py", line 19, in _main
    ytdl_sub.cli.main.main()
  File "/Applications/ytdl-sub/src/ytdl_sub/cli/main.py", line 174, in main
    transaction_logs = _download_subscriptions_from_yaml_files(config=config, args=args)
  File "/Applications/ytdl-sub/src/ytdl_sub/cli/main.py", line 60, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=args.dry_run)
  File "/Applications/ytdl-sub/src/ytdl_sub/subscriptions/subscription_download.py", line 288, in download
    for entry in downloader.download():
  File "/Applications/ytdl-sub/src/ytdl_sub/downloaders/downloader.py", line 582, in download
    for entry in self._download(parents=parents, orphans=orphan_entries):
  File "/Applications/ytdl-sub/src/ytdl_sub/downloaders/downloader.py", line 560, in _download
    for entry_child in self._download_parent_entry(parent=parent):
  File "/Applications/ytdl-sub/src/ytdl_sub/downloaders/downloader.py", line 498, in _download_parent_entry
    for entry_child in self._download_entries(parent.entry_children()):
  File "/Applications/ytdl-sub/src/ytdl_sub/downloaders/downloader.py", line 494, in _download_entries
    yield self._download_entry(entry)
  File "/Applications/ytdl-sub/src/ytdl_sub/downloaders/downloader.py", line 450, in _download_entry
    download_entry = self._extract_entry_info_with_retry(entry=entry)
  File "/Applications/ytdl-sub/src/ytdl_sub/downloaders/downloader.py", line 439, in _extract_entry_info_with_retry
    download_entry_dict = self.extract_info_with_retry(
  File "/Applications/ytdl-sub/src/ytdl_sub/downloaders/downloader.py", line 299, in extract_info_with_retry
    raise FileNotDownloadedException(
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads/rick_a/%(id)s.%(ext)s', 'writethumbnail': True, 'download_archive': '.ytdl-sub-downloads/rick_a/.ytdl-sub-rick_a-download-archive.txt', 'daterange': <yt_dlp.utils.DateRange object at 0x109b99000>, 'break_on_reject': True, 'postprocessors': [{'key': 'FFmpegVideoRemuxer', 'when': 'post_process', 'preferedformat': 'mp4'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'format': 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best', 'break_on_existing': True}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=zN_GNb_QXKk'}}
```

[ytdl-sub.gg03c0ds.txt](https://github.com/jmbannon/ytdl-sub/files/10711744/ytdl-sub.gg03c0ds.txt)

**Comment by DaveAlton** [comment]
I wasn’t using docker correctly
