### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type

### ISSUE THREAD

**Issue by howlerwolf1313** [jmbannon/ytdl-sub#590]
Getting this error while executing in freebsd 13.1 inside a jail, installed via PIP

```
root@unrar:~ # ytdl-sub view
Traceback (most recent call last):
  File "/usr/local/bin/ytdl-sub", line 5, in <module>
    from ytdl_sub.main import main
  File "/config/ytdl-sub/src/ytdl_sub/main.py", line 3, in <module>
    from ytdl_sub.cli.main_args_parser import parser
  File "/config/ytdl-sub/src/ytdl_sub/cli/main_args_parser.py", line 6, in <module>
    from ytdl_sub.utils.logger import LoggerLevels
  File "/config/ytdl-sub/src/ytdl_sub/utils/logger.py", line 13, in <module>
    from ytdl_sub.utils.file_handler import FileHandler
  File "/config/ytdl-sub/src/ytdl_sub/utils/file_handler.py", line 17, in <module>
    def get_file_extension(file_name: Path | str) -> str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

**Comment by jmbannon** [comment]
I think it might be a bug from not passing a URL after view. Can you try pasting any YT vid URL and see if that works?

**Comment by jmbannon** [comment]
Oh actually I know why - you are using an older version of python. You need python >= 3.10
