### ISSUE TITLE
Faced with a "OSError: [Errno 24] Too many open files" after download 300+ videos

### ISSUE THREAD

**Issue by jinnotgin** [jmbannon/ytdl-sub#598]
Faced the following issues twice when downloading videos off a YouTube channel. Here is the ending error log of the 2nd time I saw this issue:

## Log file
```
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "ytdl_sub/subscriptions/subscription_download.py", line 118, in _prepare_working_directory
  File "ytdl_sub/subscriptions/subscription_download.py", line 169, in _subscription_download_context_managers
  File "ytdl_sub/subscriptions/subscription_download.py", line 302, in _process_subscription
  File "ytdl_sub/downloaders/url/downloader.py", line 533, in download
  File "ytdl_sub/downloaders/url/downloader.py", line 399, in _extract_entry_info_with_retry
  File "ytdl_sub/downloaders/ytdlp.py", line 93, in extract_info_with_retry
  File "ytdl_sub/downloaders/ytdlp.py", line 54, in extract_info
  File "contextlib.py", line 135, in __enter__
  File "ytdl_sub/downloaders/ytdlp.py", line 38, in ytdlp_downloader
  File "yt_dlp/YoutubeDL.py", line 740, in __init__
  File "yt_dlp/YoutubeDL.py", line 3887, in _setup_opener
  File "yt_dlp/utils.py", line 1038, in make_HTTPS_handler
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ytdl_sub/main.py", line 26, in main
  File "ytdl_sub/main.py", line 18, in _main
  File "ytdl_sub/cli/main.py", line 325, in main
  File "ytdl_sub/cli/main.py", line 110, in _download_subscriptions_from_yaml_files
  File "ytdl_sub/subscriptions/subscription_download.py", line 350, in download
  File "ytdl_sub/subscriptions/subscription_download.py", line 297, in _process_subscription
  File "contextlib.py", line 153, in __exit__
  File "ytdl_sub/subscriptions/subscription_download.py", line 164, in _subscription_download_context_managers
  File "contextlib.py", line 153, in __exit__
  File "ytdl_sub/subscriptions/subscription_download.py", line 120, in _prepare_working_directory
  File "ytdl_sub/subscriptions/subscription_download.py", line 106, in _delete_working_directory
  File "shutil.py", line 721, in rmtree
  File "shutil.py", line 718, in rmtree
OSError: [Errno 24] Too many open files: '.ytdl-sub-downloads/healthygamergg'
[ytdl-sub] Version 2023.04.20+d5d9978
```

Here are my configs:

## config.yaml
```yaml
# This config uses prebuilt presets included with ytdl-sub to download and format
# channels from YouTube or other sites supported by yt-dlp into a TV show for
# your favorite player. The directory format will look something like
#
#   /tv_shows
#       /Season 2021
#           s2021.e0317 - Pattys Day Video-thumb.jpg
#           s2021.e0317 - Pattys Day Video.mp4
#           s2021.e0317 - Pattys Day Video.nfo
#       /Season 2022
#           s2022.e1225 - Merry Christmas-thumb.jpg
#           s2022.e1225 - Merry Christmas.mp4
#           s2022.e1225 - Merry Christmas.nfo
#       poster.jpg
#       fanart.jpg
#       tvshow.nfo
#
# The idea is to use dates as numerics to represent season and episode numbers.
configuration:
  working_directory: ".ytdl-sub-downloads"

presets:
  # Your main TV show preset - all your tv show subscriptions will use this.
  tv_show:
    preset:
      # Choose one of the following player types:
      # - "kodi_tv_show_by_date"
      # - "jellyfin_tv_show_by_date"
      # - "plex_tv_show_by_date"

      - "jellyfin_tv_show_by_date" # replace with desired player type

      # Choose one of the following season/episode formats:
      # - "season_by_year__episode_by_month_day"
      # - "season_by_year_month__episode_by_day"
      # - "season_by_year__episode_by_month_day_reversed"
      # - "season_by_year__episode_by_download_index"

      - "season_by_year__episode_by_month_day" # replace with desired season/episode format

      # Include any of the presets listed below in your 'main preset' if you want
      # it applied to every TV show. Or, use them on the individual subscriptions.
      # - "only_recent_videos"
      # - "add_subtitles"
      # - "sponsorblock"
      # - "include_info_json"

    # To download age-restricted videos, you will need to uncomment and set your cookie
    # file here as a ytdl parameter. For more info, see
    # https://ytdl-sub.readthedocs.io/en/latest/faq.html#download-age-restricted-youtube-videos
    #
    # ytdl_options:
    #   cookiefile: "/config/cookie_file.txt"  # replace with actual cookie file path

    overrides:
      tv_show_directory: "/media/smb-videos/YouTube" # replace with path to tv show directory
      # Fields in the prebuilt preset that can be changed:
      #
      # episode_title: "{upload_date_standardized} - {title}"
      # episode_plot: "{webpage_url}"  # source variable for the video description is {description}

  tv_show_archival:
    preset:
      - "tv_show"

    ytdl_options:
      break_on_existing: True # Stop downloads if it already exists

    output_options:
      maintain_download_archive: True

  ####################################################################################################

  # Preset to only download and keep recent videos
  only_recent_videos:
    # Only download videos within the download_range
    date_range:
      after: "today-{download_range}"

    # Stops fetching metadata if the video is out of range (saves time + bandwidth)
    ytdl_options:
      break_on_reject: True

    # Deletes any videos older than download_range. WARNING: do not use
    # "season_by_year__episode_by_download_index" if you plan to delete older videos
    output_options:
      keep_files_after: "today-{download_range}"

    # Set the duration of download_range, defaults to 2 months
    overrides:
      download_range: "2months"

  ####################################################################################################

  # Preset to download subtitles (either by file or embedded)
  add_subtitles:
    subtitles:
      # Embed subtitles into the video
      embed_subtitles: True
      # And/or download them as a file. Uncomment to download as file:
      # subtitles_name: "{episode_file_path}.{lang}.{subtitles_ext}"
      # subtitles_type: "srt"

      languages: "en" # supports list of multiple languages
      allow_auto_generated_subtitles: True # allow auto subtitles

  ####################################################################################################

  # Preset to cut sponsor segments from videos
  sponsorblock:
    # If you download using cron, it is wise to add a delay before downloading ad-filled content to
    # give folks time to submit sponsor segments. Uncomment to wait 2 days before download a video.
    date_range:
      before: "today-2days"

    chapters:
      # Remove all of these sponsorblock categories
      sponsorblock_categories:
        - "intro"
        - "outro"
        - "selfpromo"
        - "preview"
        - "interaction"
        - "sponsor"
        - "music_offtopic"
      remove_sponsorblock_categories: "all"
      force_key_frames: False

  ####################################################################################################


  # Preset for the hoarders who want to also save the info.json file
  include_info_json:
    output_options:
      info_json_name: "{episode_file_path}.{info_json_ext}"
```

## subscriptions.yaml
```yaml
# Define any number subscriptions in a single file, or use multiple
# files to organize (i.e by genre)

healthygamergg:
  # Mix and match any number of presets to use. You can either lump all settings into
  # a single preset to save some lines, or modularize them and use many.
  preset:
    - "tv_show_archival"

  overrides:
    # Required to specify for every subscription
    tv_show_name: "HealthyGamerGG"
    url: "https://www.youtube.com/channel/UClHVl2N3jPEbkNJVx-ItQIQ"
    # Optional
    # tv_show_genre: "Music"
```

I've also included a zipped full log file for reference as well: [ytdl-sub.5iv83cu9.zip](https://github.com/jmbannon/ytdl-sub/files/11330845/ytdl-sub.5iv83cu9.zip)

Running this off a Ubuntu 22.04 server environment.

**Comment by jmbannon** [comment]
The error comes from yt-dlp, my guess is they leave some files open somewhere, and blows up after 300 vids. A good work around is to use this prebuilt preset:
https://ytdl-sub.readthedocs.io/en/latest/presets.html#chunk-initial-download

And adjust the max_downloads to your liking. This will also help with 'rotating' the channels you download, so you aren't stuck on a single one until it's finished.

Going to close this issue since it's technically not a ytld-sub bug - might be worth reporting in yt-dlp.

**Comment by jmbannon** [comment]
Do you by chance have other apps running on the same machine that could be opening tons of files? Practically everywhere in ytdl-sub uses `with open(...)` which should automatically close the file after use, so I don't think it's coming from ytdl-sub. We've also had other power-users downloading thousands of videos and never had this come up before

**Comment by jinnotgin** [comment]
Hmm. I'm unsure of the activity at the point in time (this is my Jellyfin server machine), as its possible that there were other services (e.g Jellyfin, Nextcloud) at the time that may have been requesting for resources. 

Another point that may be of interest is that my path (tv_show_directory: "/media/smb-videos/YouTube") is actually a Samba share. It is also possible that its something related to Samba, which might be related to possible unclosed files? May also explain why other power-users never had such issues before.

Anyway, I'm not being blocked by this issue, as I've already did the initial download the video backlog that I need.

**Comment by jmbannon** [comment]
Yeah hard to say exactly - but glad you worked around it
