### ISSUE TITLE
NoneType Error when first of two regex.match capture groups is not matched

### ISSUE THREAD

**Issue by Svagtlys** [jmbannon/ytdl-sub#613]
I set up some regex to parse out the artist/title from the base title, but when the first capture group doesn't exist and the second does, ytdl-sub seems to ignore the capture_group_defaults and throw an error instead. I've done some troubleshooting and this is definitely the cause; turning the first capture group into a non-capturing group and removing the related variables prevents the error, and base titles that result in both groups being captured also don't throw the error.  I'm unsure if I'm misunderstanding the use of capture_group_defaults or if there's some other issue here.

Regex (matches 'throwaway - artist - title (throwaway)', but in some cases will only match 'title'):

```
regex:
  from:
    title:
      match: "^(?:(.+?)(?= - | \\/{2} )(?: - | \\/{2} ))*([^\\[\\{\\(\\|]*?)\\s*(?=\\{|\\(|\\||\\[|$).*"
      capture_group_names:
        - "captured_track_artist"        
        - "captured_track_title"        
      capture_group_defaults:
        - "{creator}"
        - "{title}"
```

Log:
```[ytdl-sub] Beginning CLI dry run
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '/config/.ytdl-sub-downloads/cli-dl-a4d5d014/%(id)s.%(ext)s', 'writethumbnail': False, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '/config/.ytdl-sub-downloads/cli-dl-a4d5d014/.ytdl-sub-cli-dl-a4d5d014-download-archive.txt', 'break_on_existing': 'True', 'max_downloads': 3, 'skip_download': True, 'writeinfojson': True}
[ytdl-sub:yt-dlp] [youtube] Extracting URL: https://www.youtube.com/watch?v=Zso4Qa1sVek
[ytdl-sub:yt-dlp] [youtube] Zso4Qa1sVek: Downloading webpage
[ytdl-sub:yt-dlp] [youtube] Zso4Qa1sVek: Downloading android player API JSON
[ytdl-sub:yt-dlp] [info] Zso4Qa1sVek: Downloading 1 format(s): 315+251
[ytdl-sub:yt-dlp] [info] Writing video metadata as JSON to: /config/.ytdl-sub-downloads/cli-dl-a4d5d014/Zso4Qa1sVek.info.json
[ytdl-sub:downloader] Beginning downloads for https://www.youtube.com/watch?v=Zso4Qa1sVek
[ytdl-sub:downloader] Downloading entry 1/1: Frugal Wizard Update + Weekly Update
[ytdl-sub:downloader] Downloading metadata for Frugal Wizard Update + Weekly Update
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '/config/.ytdl-sub-downloads/cli-dl-a4d5d014/%(id)s.%(ext)s', 'writethumbnail': False, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '/config/.ytdl-sub-downloads/cli-dl-a4d5d014/.ytdl-sub-cli-dl-a4d5d014-download-archive.txt', 'postprocessors': [{'key': 'FFmpegExtractAudio', 'when': 'post_process', 'preferredcodec': 'mp3', 'preferredquality': 320}], 'break_on_existing': 'True', 'max_downloads': 3, 'skip_download': True}
[ytdl-sub:yt-dlp] [youtube] Extracting URL: https://www.youtube.com/watch?v=Zso4Qa1sVek
[ytdl-sub:yt-dlp] [youtube] Zso4Qa1sVek: Downloading webpage
[ytdl-sub:yt-dlp] [youtube] Zso4Qa1sVek: Downloading android player API JSON
[ytdl-sub:yt-dlp] [info] Zso4Qa1sVek: Downloading 1 format(s): 315+251
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 26, in main
    _main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 18, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 335, in main
    _download_subscription_from_cli(
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 158, in _download_subscription_from_cli
    return subscription, subscription.download(dry_run=dry_run)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 350, in download
    return self._process_subscription(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 312, in _process_subscription
    self._process_entry(
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 236, in _process_entry
    if (entry_ := plugin.modify_entry(entry_)) is None:
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/plugins/regex.py", line 325, in modify_entry
    variables_to_add={
                     ^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/plugins/regex.py", line 326, in <dictcomp>
    f"{regex_options.capture_group_names[i]}_sanitized": sanitize_filename(
                                                         ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/utils.py", line 715, in sanitize_filename
    s = re.sub(r'[0-9]+(?::[0-9]+)+', lambda m: m.group(0).replace(':', '_'), s)  # Handle timestamps
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 185, in sub
    return _compile(pattern, flags).sub(repl, string, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
[ytdl-sub] Version 2023.04.20+d5d9978
Please upload the error log file '/tmp/ytdl-sub.2yhrnpwg' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!```

**Comment by jmbannon** [comment]
You could probably also simplify your regex string by splitting up the ORs into separate list entries. The plugin works by trying to match using each regex from top-to-bottom.

**Comment by jmbannon** [comment]
You can see it in use in this example here: https://github.com/jmbannon/ytdl-sub/blob/master/examples/music_audio_subscriptions.yaml#L65

**Comment by Svagtlys** [comment]
Ah yeah, I didn't consider that the match might support a list, that would definitely make it simpler. 

Thanks for clarifying on the use of regex match. I guess I'll leave the artist capture out, though, no point capturing potentially nothing and overwriting the probably fine creator metadata, it was mostly just for a couple edge cases.

**Comment by jmbannon** [comment]
Do you mind sharing the URL you're trying to scrape? Assuming it could contain multiple artists, maybe there is another way to get their values
