### ISSUE TITLE
 FileNotDownloadedException - Logs Attached

### ISSUE THREAD

**Issue by alxjsn** [jmbannon/ytdl-sub#614]
Haven't debugged the issue, just uploading here for someone who might quickly find out what's wrong.

```
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 26, in main
    _main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 18, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 325, in main
    transaction_logs = _download_subscriptions_from_yaml_files(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 110, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=dry_run)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 350, in download
    return self._process_subscription(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 302, in _process_subscription
    entry = downloader.download(entry)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 546, in download
    download_entry = self._extract_entry_info_with_retry(entry=entry)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 402, in _extract_entry_info_with_retry
    download_entry_dict = YTDLP.extract_info_with_retry(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/ytdlp.py", line 127, in extract_info_with_retry
    raise FileNotDownloadedException(
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads/bsidessf/%(id)s.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '.ytdl-sub-downloads/bsidessf/.ytdl-sub-bsidessf-download-archive.txt', 'writesubtitles': True, 'postprocessors': [{'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': True}, {'key': 'SponsorBlock', 'when': 'pre_process', 'categories': ['intro', 'outro', 'selfpromo', 'preview', 'interaction', 'sponsor', 'music_offtopic']}, {'key': 'ModifyChapters'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'ModifyChapters', 'force_keyframes': False, 'remove_sponsor_segments': ['outro', 'music_offtopic', 'sponsor', 'selfpromo', 'preview', 'interaction', 'intro']}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'writeautomaticsub': True, 'subtitleslangs': ['en'], 'break_on_existing': True, 'format': "(bv*[ext=mp4][vcodec~='^((he|a)vc|h26[45])']+ba[ext=m4a]) / (bv[ext=mp4]*+ba[ext=m4a]/b)", 'break_on_reject': True}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=XpjfZvpmEPE'}}
[ytdl-sub] Version 2023.05.18+0497f2b
```
[debug.zip](https://github.com/jmbannon/ytdl-sub/files/11517441/debug.zip)

**Comment by alxjsn** [comment]
Hmm so I actually ran into this about 8 hours ago and then ran it again before I submitted here. I noticed when I pass the YouTube URL that failed to yt-dlp directly it'll throw a bunch of 500 errors before getting a file successfully.

**Comment by jmbannon** [comment]
Hmm, maybe it's throwing 500 on getting the thumbnail

**Comment by alxjsn** [comment]
It's possible this might be my issue: https://github.com/yt-dlp/yt-dlp/issues/502#issuecomment-928925464

Would there be any pitfalls in ytdl-sub in specific if I used `--check-formats`?

**Comment by jmbannon** [comment]
> Would there be any pitfalls in ytdl-sub in specific if I used `--check-formats`?

Not sure what exactly that does but fwiw we do check if the thumbnail exists by checking if it's jpg or webp

**Comment by alxjsn** [comment]
Using that option fixed it for this specific channel so I'll close this out.

**Comment by jmbannon** [comment]
> Using that option fixed it for this specific channel so I'll close this out.
> 
> ```
> check_formats:
>     ytdl_options:
>       check_formats: True
> ```

Hmmm, so does it redownload if it's not the right format? Maybe we should have this on by default

**Comment by alxjsn** [comment]
Right now I have it so that I can just apply the preset to problematic channels since this comment says it could slow things down: https://github.com/yt-dlp/yt-dlp/issues/502#issuecomment-928925464
