### ISSUE TITLE
raspberry pi 4

### ISSUE THREAD

**Issue by thisisawesome1994** [jmbannon/ytdl-sub#652]
First of all, you closed my ticket without any questions.

Second of all, this are my errors in python and command lines using the raspberry pi 4

uname -a
Linux plex 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux

for the python app

ytdl-sub sub subscriptions.yaml
Traceback (most recent call last):
File "/usr/local/bin/ytdl-sub", line 5, in
from ytdl_sub.main import main
File "/usr/local/lib/python3.9/dist-packages/ytdl_sub/main.py", line 3, in
from ytdl_sub.cli.main_args_parser import parser
File "/usr/local/lib/python3.9/dist-packages/ytdl_sub/cli/main_args_parser.py", line 6, in
from ytdl_sub.utils.logger import LoggerLevels
File "/usr/local/lib/python3.9/dist-packages/ytdl_sub/utils/logger.py", line 13, in
from ytdl_sub.utils.file_handler import FileHandler
File "/usr/local/lib/python3.9/dist-packages/ytdl_sub/utils/file_handler.py", line 17, in
def get_file_extension(file_name: Path | str) -> str:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

the executable also dont work, while I have 64 bit arm64.

cannot execute binary file: Exec format error

**Comment by jmbannon** [comment]
I commented on the original, let's move the discussion there again https://github.com/jmbannon/ytdl-sub/issues/651
