### ISSUE TITLE
Unable to download a video from a channel

### ISSUE THREAD

**Issue by dreamonates** [jmbannon/ytdl-sub#679]
i've been having this problem with downloading a youtube video from a nostalgia channel. i've downloaded the rest of the channel fine but it stopped working.

same thing happened when i tried to start downloading another channel. is it because of a ban from youtube api?

i've attached the error log, config and subscriptions .yaml as .txt files.

it was working fine with a few channels but suddenly stopped right now.
thanks in advance.

using the latest build of ytdl-sub.

[subscriptions.txt](https://github.com/jmbannon/ytdl-sub/files/12226639/subscriptions.txt)
[config.txt](https://github.com/jmbannon/ytdl-sub/files/12226641/config.txt)
[6wzuv35c.txt](https://github.com/jmbannon/ytdl-sub/files/12226645/6wzuv35c.txt)

excerpt from the error:
```[ytdl-sub:yt-dlp] ERROR: 
[download] Got error: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2576)
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "C:\Users\ates_\ytdl-sub\src\ytdl_sub\main.py", line 26, in main
    _main()
  File "C:\Users\ates_\ytdl-sub\src\ytdl_sub\main.py", line 18, in _main
    ytdl_sub.cli.main.main()
  File "C:\Users\ates_\ytdl-sub\src\ytdl_sub\cli\main.py", line 326, in main
    transaction_logs = _download_subscriptions_from_yaml_files(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ates_\ytdl-sub\src\ytdl_sub\cli\main.py", line 110, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=dry_run)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ates_\ytdl-sub\src\ytdl_sub\subscriptions\subscription_download.py", line 347, in download
    return self._process_subscription(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ates_\ytdl-sub\src\ytdl_sub\subscriptions\subscription_download.py", line 297, in _process_subscription
    entry = downloader.download(entry)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ates_\ytdl-sub\src\ytdl_sub\downloaders\url\downloader.py", line 492, in download
    download_entry = self._extract_entry_info_with_retry(entry=entry)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ates_\ytdl-sub\src\ytdl_sub\downloaders\url\downloader.py", line 348, in _extract_entry_info_with_retry
    download_entry_dict = YTDLP.extract_info_with_retry(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ates_\ytdl-sub\src\ytdl_sub\downloaders\ytdlp.py", line 137, in extract_info_with_retry
    raise FileNotDownloadedException(
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads\\DDKR TV Arşivi\\%(id)s.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': 'ffmpeg.exe', 'download_archive': '.ytdl-sub-downloads\\DDKR TV Arşivi\\.ytdl-sub-DDKR TV Arşivi-download-archive.json', 'postprocessors': [{'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'break_on_existing': True, 'break_on_reject': True, 'cookiefile': 'C:\\Users\\ates_\\ytdl-sub\\cookies.txt'}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=mOsrsPW_sAs'}}```
[ytdl-sub] Version 2023.03.24+14e4a4b
Please upload the error log file 'C:\Users\ates_\AppData\Local\Temp\ytdl-sub.6wzuv35c' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!

**Comment by dreamonates** [comment]
it got fixed by itself after i changed the ip, so it has to be because of a ban by youtube :)

**Comment by dreamonates** [comment]
problem solved.
