### ISSUE TITLE
Can't download a channel

### ISSUE THREAD

**Issue by dreamonates** [jmbannon/ytdl-sub#681]
i wanted to download a channel that uploads old tv broadcasts. it starts downloading fine but stops suddenly at the beginning.

attached required files as .txt files.

[ytdl-sub.qtuze72h.txt](https://github.com/jmbannon/ytdl-sub/files/12250505/ytdl-sub.qtuze72h.txt)
[config.txt](https://github.com/jmbannon/ytdl-sub/files/12250507/config.txt)
[subscriptions.txt](https://github.com/jmbannon/ytdl-sub/files/12250508/subscriptions.txt)

thanks in advance. 

i got recent builds of python and ffmpeg installed.

excerpt from the error:
 ```[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "ytdl_sub\main.py", line 26, in main
  File "ytdl_sub\main.py", line 18, in _main
  File "ytdl_sub\cli\main.py", line 326, in main
  File "ytdl_sub\cli\main.py", line 110, in _download_subscriptions_from_yaml_files
  File "ytdl_sub\subscriptions\subscription_download.py", line 347, in download
  File "ytdl_sub\subscriptions\subscription_download.py", line 307, in _process_subscription
  File "ytdl_sub\subscriptions\subscription_download.py", line 235, in _process_entry
  File "ytdl_sub\subscriptions\subscription_download.py", line 210, in _post_process_entry
  File "ytdl_sub\plugins\video_tags.py", line 84, in post_process_entry
  File "ytdl_sub\utils\ffmpeg.py", line 207, in add_ffmpeg_metadata_key_values
  File "ytdl_sub\utils\ffmpeg.py", line 93, in run
  File "subprocess.py", line 526, in run
subprocess.CalledProcessError: Command '['ffmpeg.exe', '-i', '.ytdl-sub-downloads\\Tv Arşiv Delisi\\a_iRT1G0TGE.mp4', '-map', '0', '-dn', '-metadata', 'show=Tv Arşiv Delisi', '-metadata', 'genre=ytdl-sub', '-metadata', 'episode_id=100804', '-metadata', 'title=2018-10-08 - Tea and Sympathy 1956 HBB', '-metadata', 'synopsis=https://www.youtube.com/watch?v=a_iRT1G0TGE\n\n', '-metadata', 'year=2018', '-metadata', 'date=2018-10-08', '-metadata', 'contentRating=TV-14', '-codec', 'copy', '.ytdl-sub-downloads\\Tv Arşiv Delisi\\a_iRT1G0TGE.mp4.out.mp4']' returned non-zero exit status 1.
[ytdl-sub] Version 2023.07.30+85c98f2
Please upload the error log file 'C:\Users\ates_\AppData\Local\Temp\ytdl-sub.qtuze72h' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!
PS C:\Users\ates_\ytdl-sub> ```

**Comment by jmbannon** [comment]
Chan you try having the file convert just be:
```
    file_convert:
     convert_to: "mp4"
```
Wondering if the custom ffmpeg command is messing something up

**Comment by dreamonates** [comment]
removing "convert_to: mp4" made me download the rest of the channel without a single error. thank you so much.
