### ISSUE TITLE
[Bug] OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by stjep** [jmbannon/ytdl-sub#685]
Received a `OSError: [Errno 24] Too many open files` while running ytdl-sub and it asked that I provide the attached error file and YAML.

[ytdl-sub.lyvwolnl.zip](https://github.com/jmbannon/ytdl-sub/files/12274329/ytdl-sub.lyvwolnl.zip)
[YAML.zip](https://github.com/jmbannon/ytdl-sub/files/12274332/YAML.zip)

**Comment by jomonjohnn** [comment]
Encountered the same.

> Traceback (most recent call last):
>   File "ytdl_sub/subscriptions/subscription_download.py", line 123, in _prepare_working_directory
>   File "ytdl_sub/subscriptions/subscription_download.py", line 173, in _subscription_download_context_managers
>   File "ytdl_sub/subscriptions/subscription_download.py", line 297, in _process_subscription
>   File "ytdl_sub/downloaders/url/downloader.py", line 490, in download
>   File "ytdl_sub/downloaders/url/downloader.py", line 347, in _extract_entry_info_with_retry
>   File "ytdl_sub/downloaders/ytdlp.py", line 95, in extract_info_with_retry
>   File "ytdl_sub/downloaders/ytdlp.py", line 54, in extract_info
>   File "contextlib.py", line 135, in __enter__
>   File "ytdl_sub/downloaders/ytdlp.py", line 36, in ytdlp_downloader
>   File "contextlib.py", line 135, in __enter__
>   File "ytdl_sub/utils/logger.py", line 201, in handle_external_logs
>   File "ytdl_sub/utils/logger.py", line 168, in _get
>   File "ytdl_sub/utils/logger.py", line 151, in _get_debug_file_handler
>   File "logging/__init__.py", line 1169, in __init__
>   File "logging/__init__.py", line 1201, in _open
> OSError: [Errno 24] Too many open files: '/tmp/ytdl-sub.77htjdyr'
> 
> During handling of the above exception, another exception occurred:

**Comment by jmbannon** [comment]
which platform are you using to run ytdl-sub @jomonjohnn ?

**Comment by jmbannon** [comment]
It looks like the debug log (which writes to /tmp) can't write or something, then I'm guessing recursively keeps trying to log (and open another file in /tmp) until it hits this OSError
