### ISSUE TITLE
FileNotDownloadedException with max_filesize: 15M

### ISSUE THREAD

**Issue by anjerukare** [jmbannon/ytdl-sub#697]
Logs tail:
<details>
<summary>expand</summary>

```
[ytdl-sub:yt-dlp-downloader] Failed to download entry. Retrying 4 / 5
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '/tmp/ytdl-sub-downloads/cli-dl-0eacb42e/%(id)s.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'postprocessors': [{'key': 'FFmpegExtractAudio', 'when': 'post_process', 'preferredcodec': 'opus', 'preferredquality': 0}], 'break_on_existing': True, 'max_filesize': '15M', 'break_on_reject': True, 'check_formats': True}
[ytdl-sub:yt-dlp] [youtube] Extracting URL: https://www.youtube.com/watch?v=FABmGWoScDk
[ytdl-sub:yt-dlp] [youtube] FABmGWoScDk: Downloading webpage
[ytdl-sub:yt-dlp] [youtube] FABmGWoScDk: Downloading ios player API JSON
[ytdl-sub:yt-dlp] [youtube] FABmGWoScDk: Downloading android player API JSON
[ytdl-sub:yt-dlp] [youtube] FABmGWoScDk: Downloading m3u8 information
[ytdl-sub:yt-dlp] [info] Testing format 303
[ytdl-sub:yt-dlp] [info] Testing format 617
[ytdl-sub:yt-dlp] [info] Testing format 299
[ytdl-sub:yt-dlp] [info] Testing format 312
[ytdl-sub:yt-dlp] [info] Testing format 399
[ytdl-sub:yt-dlp] [info] Testing format 302
[ytdl-sub:yt-dlp] [info] Testing format 612
[ytdl-sub:yt-dlp] [info] Testing format 298
[ytdl-sub:yt-dlp] [info] Testing format 311
[ytdl-sub:yt-dlp] [info] Testing format 398
[ytdl-sub:yt-dlp] [info] Testing format 247
[ytdl-sub:yt-dlp] [info] Testing format 136
[ytdl-sub:yt-dlp] [info] Testing format 22
[ytdl-sub:yt-dlp] [info] Testing format 244
[ytdl-sub:yt-dlp] [info] Testing format 606
[ytdl-sub:yt-dlp] [info] Testing format 135
[ytdl-sub:yt-dlp] [info] Testing format 231
[ytdl-sub:yt-dlp] [info] Testing format 397
[ytdl-sub:yt-dlp] [info] Testing format 243
[ytdl-sub:yt-dlp] [info] Testing format 605
[ytdl-sub:yt-dlp] [info] Testing format 18
[ytdl-sub:yt-dlp] [info] Testing format 134
[ytdl-sub:yt-dlp] [info] Testing format 230
[ytdl-sub:yt-dlp] [info] Testing format 396
[ytdl-sub:yt-dlp] [info] Testing format 242
[ytdl-sub:yt-dlp] [info] Testing format 604
[ytdl-sub:yt-dlp] [info] Testing format 133
[ytdl-sub:yt-dlp] [info] Testing format 229
[ytdl-sub:yt-dlp] [info] Testing format 395
[ytdl-sub:yt-dlp] [info] Testing format 278
[ytdl-sub:yt-dlp] [info] Testing format 603
[ytdl-sub:yt-dlp] [info] Testing format 160
[ytdl-sub:yt-dlp] [info] Testing format 269
[ytdl-sub:yt-dlp] [info] Testing format 394
[ytdl-sub:yt-dlp] [info] Testing format 17
[ytdl-sub:yt-dlp] [info] Testing format 251
[ytdl-sub:yt-dlp] [info] Testing format 140
[ytdl-sub:yt-dlp] [info] Testing format 250
[ytdl-sub:yt-dlp] [info] Testing format 249
[ytdl-sub:yt-dlp] [info] Testing format 139
[ytdl-sub:yt-dlp] [info] Testing format 234
[ytdl-sub:yt-dlp] [info] Testing format 233
[ytdl-sub:yt-dlp] [info] Testing format sb0
[ytdl-sub:yt-dlp] [info] Testing format sb1
[ytdl-sub:yt-dlp] [info] Testing format sb2
[ytdl-sub:yt-dlp] [info] Testing thumbnail 41
[ytdl-sub:yt-dlp] [info] Unable to connect to thumbnail 41 URL 'https://i.ytimg.com/vi_webp/FABmGWoScDk/maxresdefault.webp' - HTTP Error 404: Not Found. Skipping...
[ytdl-sub:yt-dlp] [info] Testing thumbnail 40
[ytdl-sub:yt-dlp] [info] Unable to connect to thumbnail 40 URL 'https://i.ytimg.com/vi/FABmGWoScDk/maxresdefault.jpg' - HTTP Error 404: Not Found. Skipping...
[ytdl-sub:yt-dlp] [info] Testing thumbnail 39
[ytdl-sub:yt-dlp] [info] Unable to connect to thumbnail 39 URL 'https://i.ytimg.com/vi_webp/FABmGWoScDk/hq720.webp' - HTTP Error 404: Not Found. Skipping...
[ytdl-sub:yt-dlp] [info] Testing thumbnail 38
[ytdl-sub:yt-dlp] [info] Unable to connect to thumbnail 38 URL 'https://i.ytimg.com/vi/FABmGWoScDk/hq720.jpg' - HTTP Error 404: Not Found. Skipping...
[ytdl-sub:yt-dlp] [info] Testing thumbnail 37
[ytdl-sub:yt-dlp] [info] Testing thumbnail 36
[ytdl-sub:yt-dlp] [info] Testing thumbnail 35
[ytdl-sub:yt-dlp] [info] Testing thumbnail 34
[ytdl-sub:yt-dlp] [info] Testing thumbnail 33
[ytdl-sub:yt-dlp] [info] Testing thumbnail 32
[ytdl-sub:yt-dlp] [info] Testing thumbnail 31
[ytdl-sub:yt-dlp] [info] Testing thumbnail 30
[ytdl-sub:yt-dlp] [info] Testing thumbnail 29
[ytdl-sub:yt-dlp] [info] Testing thumbnail 28
[ytdl-sub:yt-dlp] [info] Testing thumbnail 27
[ytdl-sub:yt-dlp] [info] Testing thumbnail 26
[ytdl-sub:yt-dlp] [info] Testing thumbnail 25
[ytdl-sub:yt-dlp] [info] Testing thumbnail 24
[ytdl-sub:yt-dlp] [info] Testing thumbnail 23
[ytdl-sub:yt-dlp] [info] Testing thumbnail 22
[ytdl-sub:yt-dlp] [info] Testing thumbnail 21
[ytdl-sub:yt-dlp] [info] Testing thumbnail 20
[ytdl-sub:yt-dlp] [info] Testing thumbnail 19
[ytdl-sub:yt-dlp] [info] Testing thumbnail 18
[ytdl-sub:yt-dlp] [info] Testing thumbnail 17
[ytdl-sub:yt-dlp] [info] Testing thumbnail 16
[ytdl-sub:yt-dlp] [info] Testing thumbnail 15
[ytdl-sub:yt-dlp] [info] Testing thumbnail 14
[ytdl-sub:yt-dlp] [info] Testing thumbnail 13
[ytdl-sub:yt-dlp] [info] Testing thumbnail 12
[ytdl-sub:yt-dlp] [info] Testing thumbnail 11
[ytdl-sub:yt-dlp] [info] Testing thumbnail 10
[ytdl-sub:yt-dlp] [info] Testing thumbnail 9
[ytdl-sub:yt-dlp] [info] Testing thumbnail 8
[ytdl-sub:yt-dlp] [info] Testing thumbnail 7
[ytdl-sub:yt-dlp] [info] Testing thumbnail 6
[ytdl-sub:yt-dlp] [info] Testing thumbnail 5
[ytdl-sub:yt-dlp] [info] Testing thumbnail 4
[ytdl-sub:yt-dlp] [info] Testing thumbnail 3
[ytdl-sub:yt-dlp] [info] Testing thumbnail 2
[ytdl-sub:yt-dlp] [info] Testing thumbnail 1
[ytdl-sub:yt-dlp] [info] Testing thumbnail 0
[ytdl-sub:yt-dlp] [info] FABmGWoScDk: Downloading 1 format(s): 303+251
[ytdl-sub:yt-dlp] Deleting existing file /tmp/ytdl-sub-downloads/cli-dl-0eacb42e/FABmGWoScDk.webp
[ytdl-sub:yt-dlp] [info] Downloading video thumbnail 37 ...
[ytdl-sub:yt-dlp] [info] Writing video thumbnail 37 to: /tmp/ytdl-sub-downloads/cli-dl-0eacb42e/FABmGWoScDk.webp
[ytdl-sub:yt-dlp] ERROR: '>' not supported between instances of 'int' and 'str'
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 26, in main
    _main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 18, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 336, in main
    _download_subscription_from_cli(
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 158, in _download_subscription_from_cli
    return subscription, subscription.download(dry_run=dry_run)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 347, in download
    return self._process_subscription(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 297, in _process_subscription
    entry = downloader.download(entry)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 492, in download
    download_entry = self._extract_entry_info_with_retry(entry=entry)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 348, in _extract_entry_info_with_retry
    download_entry_dict = YTDLP.extract_info_with_retry(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/ytdlp.py", line 137, in extract_info_with_retry
    raise FileNotDownloadedException(
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '/tmp/ytdl-sub-downloads/cli-dl-0eacb42e/%(id)s.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '/tmp/ytdl-sub-downloads/cli-dl-0eacb42e/.ytdl-sub-cli-dl-0eacb42e-download-archive.json', 'postprocessors': [{'key': 'FFmpegExtractAudio', 'when': 'post_process', 'preferredcodec': 'opus', 'preferredquality': 0}], 'break_on_existing': True, 'max_filesize': '15M', 'break_on_reject': True}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=FABmGWoScDk'}}
[ytdl-sub] Version 2023.07.30+85c98f2
Please upload the error log file '/tmp/ytdl-sub.b5zjll23' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!
```
</details>

Preset:
```yml
# ...
playlist:
  download:
    url: '{url}'

  output_options:
    output_directory: '/music'
    file_name: '{playlist_title}/{title}.{ext}'
    maintain_download_archive: true

  ytdl_options:
    break_on_existing: true
    max_filesize: 15M

  audio_extract:
    codec: 'opus'
    quality: 0

  embed_thumbnail: true

  music_tags:
    artist: '{track_artist}'
    albumartist: '{track_artist}'
    title: '{track_title}'
    year: '{upload_year}'

  regex:
    skip_if_match_fails: false

    from:
      channel:
        match: '^(.*) - Topic'
        capture_group_names: 'captured_artist'
        capture_group_defaults: '{channel}'

  overrides:
    track_artist: '{captured_artist}'
    track_title: '{title}'
# ...
```

Command:
```
ytdl-sub dl --preset playlist --download.url https://www.youtube.com/playlist?list=PL8PajZyf1KCmr3lYUPFFMEcN09S2P-VnJ
```

When I run command without `max_filesize: 15M` in config everything is ok.
Am I missing something?

**Comment by jmbannon** [comment]
> [ytdl-sub:yt-dlp] ERROR: '>' not supported between instances of 'int' and 'str'

max_filesize probably expects an int, which is size in bytes. Closing since this is a yt-dlp error, but happy to continue helping here
