### ISSUE TITLE
Download error when downloading one specific video

### ISSUE THREAD

**Issue by nitschis** [jmbannon/ytdl-sub#713]
I am pretty sure I have downloaded this video before when I did some testing, but for some reason it does not work at all anymore.

```
ytdl-sub:downloader] Downloading entry 3/21: Miniature Cooking: Pancakes | mini food tiny edible pancake | 本当に食べられるミニチュア料理 パンケーキ[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 26, in main
    _main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 18, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 326, in main
    transaction_logs = _download_subscriptions_from_yaml_files(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 110, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=dry_run)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 347, in download
    return self._process_subscription(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 297, in _process_subscription
    entry = downloader.download(entry)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 492, in download
    download_entry = self._extract_entry_info_with_retry(entry=entry)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 348, in _extract_entry_info_with_retry
    download_entry_dict = YTDLP.extract_info_with_retry(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/ytdlp.py", line 137, in extract_info_with_retry
    raise FileNotDownloadedException(
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '/config/.ytdl-sub-downloads/chibikitchen/%(id)s.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '/config/.ytdl-sub-downloads/chibikitchen/.ytdl-sub-chibikitchen-download-archive.json', 'merge_output_format': 'mp4', 'postprocessors': [{'key': 'FFmpegVideoRemuxer', 'when': 'post_process', 'preferedformat': 'mp4'}, {'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': True}, {'key': 'SponsorBlock', 'when': 'pre_process', 'categories': ['intro', 'outro', 'selfpromo', 'preview', 'interaction', 'sponsor', 'music_offtopic']}, {'key': 'ModifyChapters'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'ModifyChapters', 'force_keyframes': False, 'remove_sponsor_segments': ['interaction', 'music_offtopic', 'outro', 'intro', 'selfpromo', 'preview', 'sponsor']}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'writesubtitles': True, 'writeautomaticsub': True, 'subtitleslangs': ['en'], 'break_on_existing': True, 'format': 'bestaudio+bestvideo', 'break_on_reject': True}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=71WG-jaLW8E'}}
[ytdl-sub] Version 2023.09.02+792da1b
Please upload the error log file '/tmp/ytdl-sub.xbqey17h' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!
```

This is the output of the ytdl-sub.xbqey17h:
```
[ytdl-sub:yt-dlp] WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[ytdl-sub:yt-dlp] [youtube] 71WG-jaLW8E: Downloading initial data API JSON
[ytdl-sub:yt-dlp] [info] 71WG-jaLW8E: Downloading subtitles: en
[ytdl-sub:yt-dlp] [info] Testing format 313
[ytdl-sub:yt-dlp] [info] Testing format 271
[ytdl-sub:yt-dlp] [info] Testing format 248
[ytdl-sub:yt-dlp] [info] Testing format 137
[ytdl-sub:yt-dlp] [info] Testing format 247
[ytdl-sub:yt-dlp] [info] Testing format 136
[ytdl-sub:yt-dlp] [info] Testing format 22
[ytdl-sub:yt-dlp] [info] Testing format 244
[ytdl-sub:yt-dlp] [info] Testing format 135
[ytdl-sub:yt-dlp] [info] Testing format 243
[ytdl-sub:yt-dlp] [info] Testing format 18
[ytdl-sub:yt-dlp] [info] Testing format 134
[ytdl-sub:yt-dlp] [info] Testing format 242
[ytdl-sub:yt-dlp] [info] Testing format 133
[ytdl-sub:yt-dlp] [info] Testing format 278
[ytdl-sub:yt-dlp] [info] Testing format 160
[ytdl-sub:yt-dlp] [info] Testing format 17
[ytdl-sub:yt-dlp] [info] Testing format 251
[ytdl-sub:yt-dlp] [info] Testing format 140
[ytdl-sub:yt-dlp] [info] Testing format 250
[ytdl-sub:yt-dlp] [info] Testing format 249
[ytdl-sub:yt-dlp] [info] Testing format 139
[ytdl-sub:yt-dlp] [info] Testing format sb0
[ytdl-sub:yt-dlp] [info] Testing format sb1
[ytdl-sub:yt-dlp] [info] Testing format sb2
[ytdl-sub:yt-dlp] [info] Testing thumbnail 41
[ytdl-sub:yt-dlp] [info] Testing thumbnail 40
[ytdl-sub:yt-dlp] [info] Testing thumbnail 39
[ytdl-sub:yt-dlp] [info] Testing thumbnail 38
[ytdl-sub:yt-dlp] [info] Testing thumbnail 37
[ytdl-sub:yt-dlp] [info] Testing thumbnail 36
[ytdl-sub:yt-dlp] [info] Testing thumbnail 35
[ytdl-sub:yt-dlp] [info] Testing thumbnail 34
[ytdl-sub:yt-dlp] [info] Testing thumbnail 33
[ytdl-sub:yt-dlp] [info] Testing thumbnail 32
[ytdl-sub:yt-dlp] [info] Testing thumbnail 31
[ytdl-sub:yt-dlp] [info] Testing thumbnail 30
[ytdl-sub:yt-dlp] [info] Testing thumbnail 29
[ytdl-sub:yt-dlp] [info] Testing thumbnail 28
[ytdl-sub:yt-dlp] [info] Testing thumbnail 27
[ytdl-sub:yt-dlp] [info] Testing thumbnail 26
[ytdl-sub:yt-dlp] [info] Testing thumbnail 25
[ytdl-sub:yt-dlp] [info] Testing thumbnail 24
[ytdl-sub:yt-dlp] [info] Testing thumbnail 23
[ytdl-sub:yt-dlp] [info] Testing thumbnail 22
[ytdl-sub:yt-dlp] [info] Testing thumbnail 21
[ytdl-sub:yt-dlp] [info] Testing thumbnail 20
[ytdl-sub:yt-dlp] [info] Testing thumbnail 19
[ytdl-sub:yt-dlp] [info] Testing thumbnail 18
[ytdl-sub:yt-dlp] [info] Testing thumbnail 17
[ytdl-sub:yt-dlp] [info] Testing thumbnail 16
[ytdl-sub:yt-dlp] [info] Testing thumbnail 15
[ytdl-sub:yt-dlp] [info] Testing thumbnail 14
[ytdl-sub:yt-dlp] [info] Testing thumbnail 13
[ytdl-sub:yt-dlp] [info] Testing thumbnail 12
[ytdl-sub:yt-dlp] [info] Testing thumbnail 11
[ytdl-sub:yt-dlp] [info] Testing thumbnail 10
[ytdl-sub:yt-dlp] [info] Testing thumbnail 9
[ytdl-sub:yt-dlp] [info] Testing thumbnail 8
[ytdl-sub:yt-dlp] [info] Testing thumbnail 7
[ytdl-sub:yt-dlp] [info] Testing thumbnail 6
[ytdl-sub:yt-dlp] [info] Testing thumbnail 5
[ytdl-sub:yt-dlp] [info] Testing thumbnail 4
[ytdl-sub:yt-dlp] [info] Testing thumbnail 3
[ytdl-sub:yt-dlp] [info] Testing thumbnail 2
[ytdl-sub:yt-dlp] [info] Testing thumbnail 1
[ytdl-sub:yt-dlp] [info] Testing thumbnail 0
[ytdl-sub:yt-dlp] [SponsorBlock] Fetching SponsorBlock segments
[ytdl-sub:yt-dlp] [SponsorBlock] No matching segments were found in the SponsorBlock database
[ytdl-sub:yt-dlp] [info] 71WG-jaLW8E: Downloading 1 format(s): 251+313
[ytdl-sub:yt-dlp] Deleting existing file /config/.ytdl-sub-downloads/chibikitchen/71WG-jaLW8E.en.vtt
[ytdl-sub:yt-dlp] [info] Writing video subtitles to: /config/.ytdl-sub-downloads/chibikitchen/71WG-jaLW8E.en.vtt
[ytdl-sub:yt-dlp] [download] Destination: /config/.ytdl-sub-downloads/chibikitchen/71WG-jaLW8E.en.vtt
[download]    1.00KiB at  Unknown B/s (00:00:00)
[download]    3.00KiB at    1.33MiB/s (00:00:00)
[download]    5.00KiB at    1.21MiB/s (00:00:00)
[download] 100% of    5.00KiB in 00:00:00 at 97.72KiB/s
[ytdl-sub:yt-dlp] Deleting existing file /config/.ytdl-sub-downloads/chibikitchen/71WG-jaLW8E.webp
[ytdl-sub:yt-dlp] [info] Downloading video thumbnail 41 ...
[ytdl-sub:yt-dlp] [info] Writing video thumbnail 41 to: /config/.ytdl-sub-downloads/chibikitchen/71WG-jaLW8E.webp
[ytdl-sub:yt-dlp] [download] /config/.ytdl-sub-downloads/chibikitchen/71WG-jaLW8E.f251.webm has already been downloaded
[download] 100% of    4.26MiB
[ytdl-sub:yt-dlp] [download] Resuming download at byte 159382336
[download] Got error: HTTP Error 500: Internal Server Error
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 26, in main
    _main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 18, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 326, in main
    transaction_logs = _download_subscriptions_from_yaml_files(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 110, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=dry_run)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 347, in download
    return self._process_subscription(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 297, in _process_subscription
    entry = downloader.download(entry)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 492, in download
    download_entry = self._extract_entry_info_with_retry(entry=entry)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 348, in _extract_entry_info_with_retry
    download_entry_dict = YTDLP.extract_info_with_retry(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/ytdlp.py", line 137, in extract_info_with_retry
    raise FileNotDownloadedException(
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '/config/.ytdl-sub-downloads/chibikitchen/%(id)s.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '/config/.ytdl-sub-downloads/chibikitchen/.ytdl-sub-chibikitchen-download-archive.json', 'merge_output_format': 'mp4', 'postprocessors': [{'key': 'FFmpegVideoRemuxer', 'when': 'post_process', 'preferedformat': 'mp4'}, {'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': True}, {'key': 'SponsorBlock', 'when': 'pre_process', 'categories': ['intro', 'outro', 'selfpromo', 'preview', 'interaction', 'sponsor', 'music_offtopic']}, {'key': 'ModifyChapters'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'ModifyChapters', 'force_keyframes': False, 'remove_sponsor_segments': ['interaction', 'music_offtopic', 'outro', 'intro', 'selfpromo', 'preview', 'sponsor']}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'writesubtitles': True, 'writeautomaticsub': True, 'subtitleslangs': ['en'], 'break_on_existing': True, 'format': 'bestaudio+bestvideo', 'break_on_reject': True}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=71WG-jaLW8E'}}
[ytdl-sub] Version 2023.09.02+792da1b
Please upload the error log file '/tmp/ytdl-sub.xbqey17h' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!
```

Thank you.

**Comment by nitschis** [comment]
Okay, it seems to be a problem with yt-dl(p).

I have tried to download the same video on my local install and it also causes an issue. Sorry, should have checked that beforehand.
```

yt-dlp "https://www.youtube.com/watch?v=71WG-jaLW8E"                                                                                                                                   1 ✘  base  
[youtube] Extracting URL: https://www.youtube.com/watch?v=71WG-jaLW8E
[youtube] 71WG-jaLW8E: Downloading webpage
WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 71WG-jaLW8E: Downloading ios player API JSON
[youtube] 71WG-jaLW8E: Downloading android player API JSON
[youtube] 71WG-jaLW8E: Downloading iframe API JS
[youtube] 71WG-jaLW8E: Downloading player 7ee36b0e
[youtube] 71WG-jaLW8E: Downloading web player API JSON
[youtube] 71WG-jaLW8E: Downloading m3u8 information
WARNING: [youtube] unable to extract yt initial data; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
WARNING: [youtube] Incomplete data received in embedded initial data; re-fetching using API.
[youtube] 71WG-jaLW8E: Downloading initial data API JSON
[info] 71WG-jaLW8E: Downloading 1 format(s): 313+251
[download] Destination: Miniature Cooking： Pancakes ｜ mini food tiny edible pancake ｜ 本当に食べられるミニチュア料理 パンケーキ [71WG-jaLW8E].f313.webm
[download]  57.2% of  521.27MiB at  558.44KiB/s ETA 06:49[download] Got error: HTTP Error 500: Internal Server Error. Retrying (1/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (2/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (3/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (4/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (5/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (6/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (7/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (8/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (9/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Retrying (10/10)...
[download] Got error: HTTP Error 500: Internal Server Error. Giving up after 10 retries

```
