### ISSUE TITLE
can no longer sync Breaking Points

### ISSUE THREAD

**Issue by EvanCarroll** [jmbannon/ytdl-sub#748]
[ytdl-sub.xai5fj4w.log.txt](https://github.com/jmbannon/ytdl-sub/files/12771457/ytdl-sub.xai5fj4w.log.txt)
Getting 

```
[ytdl-sub:downloader] Beginning downloads for https://www.youtube.com/@breakingpoints
[ytdl-sub:downloader] Downloading entry 1/13: REPORT: Hunter SCORED $250K From Chinese Business To Father's House | Counter Points
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 26, in main
    _main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/main.py", line 18, in _main
    ytdl_sub.cli.main.main()
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 326, in main
    transaction_logs = _download_subscriptions_from_yaml_files(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/main.py", line 110, in _download_subscriptions_from_yaml_files
    transaction_log = subscription.download(dry_run=dry_run)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 350, in download
    return self._process_subscription(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 297, in _process_subscription
    entry = downloader.download(entry)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 490, in download
    download_entry = self._extract_entry_info_with_retry(entry=entry)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 347, in _extract_entry_info_with_retry
    download_entry_dict = YTDLP.extract_info_with_retry(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/ytdlp.py", line 137, in extract_info_with_retry
    raise FileNotDownloadedException(
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-downloads/breaking_points/%(id)s.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '.ytdl-sub-downloads/breaking_points/.ytdl-sub-breaking_points-download-archive.json', 'writesubtitles': True, 'postprocessors': [{'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': True}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'writeautomaticsub': True, 'subtitleslangs': ['en'], 'format': '(bv*[height<=1080]+bestaudio/best[height<=1080])', 'match_filter': <function match_filter_func.<locals>._match_func at 0x7f5de756eca0>, 'break_on_existing': True, 'merge_output_format': 'mp4', 'break_on_reject': True}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=0OJjZ6uFrp0'}}
[ytdl-sub] Version 2023.09.28+3e41e0f
Please upload the error log file '/tmp/ytdl-sub.v_o6omf_' and make a Github issue at https://github.com/jmbannon/ytdl-sub/issues with your config and command/subscription yaml file to reproduce. Thanks for trying ytdl-sub!
```

My sub is simple

```yaml
breaking_points:
  preset:
    - "news"
  overrides:
    url: https://www.youtube.com/@breakingpoints
    tv_show_name: Breaking Points
```

and config,

```yaml
presets:
  news:
    overrides:
      tv_show_genre: "news"
    date_range:
      after: "today-{download_range}"
    ytdl_options:
      break_on_reject: True
    output_options:
      keep_files_after: "today-6month"
    overrides:
      download_range: "1month"
      tv_show_directory: "/srv/media/tv-shows"
      tv_show_genre: "news"
    preset:
      - "jellyfin_tv_show_by_date"
      - "season_by_year__episode_by_month_day_reversed"
      - max_1080p
    subtitles:
      embed_subtitles: True
      languages: "en"
      allow_auto_generated_subtitles: True
    output_options:
      info_json_name: "{episode_file_path}.{info_json_ext}"
```

**Comment by jmbannon** [comment]
In the debug logs you are getting 403 which typically means throttle. My recommendation is to try again later

**Comment by EvanCarroll** [comment]
I don't think so. Is there a way to extract the exact arguments to ytdlp rather than just the json blob that represents the options? I'd like to test it outside of ytdl-sub. I think it's trying to hit some invalid endpoint because of the options. I can easily download the same url from the same box with ytdlp

**Comment by jmbannon** [comment]
There is not, since sub uses the python API, not cli.
It could be your cookie file gets throttled

**Comment by jmbannon** [comment]
Oh wait you're not using a cookie. Maybe a vid isn't available with your format constraints?

**Comment by EvanCarroll** [comment]
@jmbannon sounds possible. Though that's a weird way to say it. How do I recreate the constraints outside of ytdl-sub to possibly file an issue upstream? Just have to manually map them to the cli?

**Comment by jmbannon** [comment]
> @jmbannon sounds possible. Though that's a weird way to say it. How do I recreate the constraints outside of ytdl-sub to possibly file an issue upstream? Just have to manually map them to the cli?

Either that or provide the yt-dlp args. In the past they've seemed cool with those

**Comment by jmbannon** [comment]
https://github.com/yt-dlp/yt-dlp/issues/7860

Looks very related to your debug logs

**Comment by jmbannon** [comment]
How much have you downloaded recently?

**Comment by jmbannon** [comment]
And also, are you on a recent ytdl-sub build?

**Comment by EvanCarroll** [comment]
I'm on the newest one, here is a self-contained test case.

```text
#!/bin/sh

mkdir config 2>&1 > /dev/null;
mkdir media 2>&1 > /dev/null;
podman rm -f ytdl-test 2>&1 > /dev/null;

cat <<EOF > ./config/config.yaml
configuration:
  working_directory: '.ytdl-sub-downloads'

presets:
  news:
    overrides:
      tv_show_genre: "news"
    date_range:
      after: "today-{download_range}"
    ytdl_options:
      break_on_reject: True
    output_options:
      keep_files_after: "today-6month"
    overrides:
      download_range: "1day"
      tv_show_directory: "/srv/media/tv-shows"
      tv_show_genre: "news"
    preset:
      - "jellyfin_tv_show_by_date"
      - "season_by_year__episode_by_month_day_reversed"
      - max_1080p
    subtitles:
      embed_subtitles: True
      languages: "en"
      allow_auto_generated_subtitles: True
    output_options:
      info_json_name: "{episode_file_path}.{info_json_ext}"
EOF

cat <<EOF > ./config/subs/news.yaml
breaking_points:
  preset:
    - "news"
  overrides:
    url: https://www.youtube.com/@breakingpoints
    tv_show_name: Breaking Points
EOF

podman run \
  --name="ytdl-test"                             \
  -e PUID=0                                      \
  -e PGID=0                                      \
  -e TZ=America/Chicago                          \
  -e DOCKER_MODS=linuxserver/mods:universal-cron \
  -v "$PWD/config:/config"                       \
  -v "$PWD/media:/srv/media"                     \
  --restart unless-stopped                       \
  ghcr.io/jmbannon/ytdl-sub:latest               \
  /usr/bin/ytdl-sub --config /config/config.yaml sub /config/subs/news.yaml
```

**Comment by EvanCarroll** [comment]
@jmbannon do you happen to get the same error with the above test?

**Comment by jmbannon** [comment]
Nope, I can download it with no issues

**Comment by jmbannon** [comment]
As I said before, you are getting 403 in your debug logs which is typically indicative of throttle by YouTube. Try using a cookies file https://github.com/jmbannon/ytdl-sub/wiki/FAQ#download-age-restricted-youtube-videos

**Comment by jmbannon** [comment]
Has been a while, any luck on this? Going to close it out since it's stale but happy to help. FYI we added a throttle protection plugin which may help prevent 403s: https://ytdl-sub.readthedocs.io/en/latest/config.html#throttle-protection

**Comment by EvanCarroll** [comment]
Yea, you were right it was throttled on youtube's side, is my guess anyway. But it wasn't throttled for days but weeks. It came through last week. But I was grinding yt hard, i think i pulled down a couple of TBs.

**Comment by EvanCarroll** [comment]
@jmbannon if you want to see why I found the issue hard to trouble shoot and was _wrongly_ suspicious of ytdl-sub, check out that feature request linked. May find it useful anyway, or something to keep in mind.
