### ISSUE TITLE
Error with Youtube archive when no videos are within the requested timeframe

### ISSUE THREAD

**Issue by Maka0** [jmbannon/ytdl-sub#81]
I've let ytdl-sub run for some channels but it errors out when a specific channel does not have a video within the requested timerange. In `config.yaml` the default 2 weeks were configured:
```yaml
configuration:
  working_directory: '/media/youtube/.cache'

presets:
  yt_channel_as_tv:
    # YouTube channels are our source/download strategy
    # Use the channel avatar and banner images for Kodi
    youtube:
      download_strategy: "channel"
      channel_avatar_path: "poster.jpg"
      channel_banner_path: "fanart.jpg"
      after: "today-2weeks"
```
Normally the archive file is created when processing a channel.

Log output:
```
[ytdl-sub:yt-dlp] [download] 2022-04-06 upload date is not in range 2022-06-16 - 9999-12-31
[ytdl-sub:downloader] RejectedVideoReached, stopping additional downloads
[ytdl-sub] An uncaught error occurred:
Traceback (most recent call last):
  File "/ytdl-sub/src/ytdl_sub/main.py", line 95, in main
    _main()
  File "/ytdl-sub/src/ytdl_sub/main.py", line 78, in _main
    _download_subscriptions_from_yaml_files(config=config, args=args)
  File "/ytdl-sub/src/ytdl_sub/main.py", line 33, in _download_subscriptions_from_yaml_files
    subscription.download()
  File "/ytdl-sub/src/ytdl_sub/subscriptions/subscription.py", line 262, in download
    with self._prepare_working_directory(), self._maintain_archive_file():
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/ytdl-sub/src/ytdl_sub/subscriptions/subscription.py", line 234, in _maintain_archive_file
    self._enhanced_download_archive.save_download_mappings()
  File "/ytdl-sub/src/ytdl_sub/ytdl_additions/enhanced_download_archive.py", line 489, in save_download_mappings
    self._download_archive = DownloadArchive.from_file(self._archive_working_file_path)
  File "/ytdl-sub/src/ytdl_sub/ytdl_additions/enhanced_download_archive.py", line 100, in from_file
    with open(file_path, "r", encoding="utf8") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/media/youtube/.cache/yt_tokyolensexplore/.ytdl-subscribe-yt_tokyolensexplore-download-archive.txt'
```

**Comment by jmbannon** [comment]
Actually decided to whip it out before starting work this morning :)
https://github.com/jmbannon/ytdl-sub/pull/83
