### ISSUE TITLE
Unable to download anything using images newer than 10.28

### ISSUE THREAD

**Issue by gythyb** [jmbannon/ytdl-sub#821]
I've used ytdl-sub for awhile, and freaking love it. It has made consuming YouTube much less annoying. I have; however, run into problems of late. Whenever I update to any image newer than 10.28, I keep getting the same error on every download, regardless of my configuration, and I don't know what next to do. I'll past the contents of the errors to see if anyone else here knows how to solve them:

`[ytdl-sub] The following error occurred for the subscription adrian_von_ziegler:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 365, in exception_handling
    yield
  File "/usr/lib/python3.11/site-packages/ytdl_sub/cli/entrypoint.py", line 113, in _download_subscriptions_from_yaml_files
    subscription.download(dry_run=dry_run)
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 352, in download
    return self._process_subscription(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 297, in _process_subscription
    entry = downloader.download(entry)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 494, in download
    download_entry = self._extract_entry_info_with_retry(entry=entry)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/url/downloader.py", line 351, in _extract_entry_info_with_retry
    download_entry_dict = YTDLP.extract_info_with_retry(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/ytdlp.py", line 95, in extract_info_with_retry
    entry_dict = cls.extract_info(
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ytdl_sub/downloaders/ytdlp.py", line 55, in extract_info
    return ytdlp.extract_info(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1556, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1567, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1723, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yt_dlp/YoutubeDL.py", line 1782, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by jmbannon** [comment]
Hello, can you provide a full log file

**Comment by gythyb** [comment]
[2023-11-19-192959.adrian_von_ziegler.error.log](https://github.com/jmbannon/ytdl-sub/files/13405657/2023-11-19-192959.adrian_von_ziegler.error.log)

**Comment by jmbannon** [comment]
You have max_downloads set to 1. There is a bug (or feature?) in yt-dlp where it really means "less than this number" which means zero (and errors). Try removing it or set it to 2

**Comment by jmbannon** [comment]
Going to close out, still happy to help!
