### ISSUE TITLE
[mediathekviewweb.de] FileNotDownloadedException

### ISSUE THREAD

**Issue by itd0** [jmbannon/ytdl-sub#867]
Hi,

I'm observing `FileNotDownloadedException`s despite successful downloads with `ytdl-sub==2023.12.29.post3`.
Sample `subscriptions.yaml`:

```yaml
---
__preset__:
  overrides: {tv_show_directory: "."}
Jellyfin TV Show by Date:
  = SWR | = Documentaries:
    "Handwerkskunst!": "https://mediathekviewweb.de/feed?query=!SWR%20%23Handwerkskunst%20%3E10&size=10000&future=true"
```

Shortened `ytdl-sub sub -l debug subscriptions.yaml` output:

```
[ytdl-sub:ytdl-options] Setting match-filters:
 - !is_live & !is_upcoming & !post_live
[ytdl-sub:ytdl-options] Setting breaking-match-filters: []
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-working-directory/Handwerkskunst!/%(id)s.%(ext)s', 'writethumbnail': False, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '.ytdl-sub-working-directory/Handwerkskunst!/.ytdl-sub-Handwerkskunst!-download-archive.json', 'match_filter': <function match_filter_func.<locals>._match_func at 0x7f036e9f2dd0>, 'break_on_existing': True, 'skip_download': True, 'writeinfojson': True}
[ytdl-sub:yt-dlp] [generic] Extracting URL: https://mediathekviewweb.de/feed?query=!SWR%20%23Handwerkskunst%20%3E10&size=10000&future=true
[ytdl-sub:yt-dlp] [generic] feed?query=!SWR #Handwerkskunst >10&size=10000&future=true: Downloading webpage
[ytdl-sub:yt-dlp] WARNING: [generic] Falling back on generic information extractor
[ytdl-sub:yt-dlp] [generic] feed?query=!SWR #Handwerkskunst >10&size=10000&future=true: Extracting information
[ytdl-sub:yt-dlp] [download] Downloading playlist: MVW - !SWR #Handwerkskunst >10 | Zukünftige
[ytdl-sub:yt-dlp] [info] Writing playlist metadata as JSON to: .ytdl-sub-working-directory/Handwerkskunst!/https：⧸⧸mediathekviewweb.de⧸feed？query=!SWR%20%23Handwerkskunst%20%3E10&size=10000&future=true.info.json
[ytdl-sub:yt-dlp] [generic] Playlist MVW - !SWR #Handwerkskunst >10 | Zukünftige: Downloading 159 items of 159
```
...
```
[ytdl-sub:yt-dlp] [info] Writing updated playlist metadata as JSON to: .ytdl-sub-working-directory/Handwerkskunst!/https：⧸⧸mediathekviewweb.de⧸feed？query=!SWR%20%23Handwerkskunst%20%3E10&size=10000&future=true.info.json
[ytdl-sub:yt-dlp] [download] Finished downloading playlist: MVW - !SWR #Handwerkskunst >10 | Zukünftige
[ytdl-sub:downloader] Beginning downloads for https://mediathekviewweb.de/feed?query=!SWR%20%23Handwerkskunst%20%3E10&size=10000&future=true
[ytdl-sub:downloader] Downloading entry 1/159: Handwerkskunst! Wie man einen Sessel polstert
[ytdl-sub:yt-dlp-downloader] ytdl_options: {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-working-directory/Handwerkskunst!/%(id)s.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '.ytdl-sub-working-directory/Handwerkskunst!/.ytdl-sub-Handwerkskunst!-download-archive.json', 'postprocessors': [{'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'break_on_existing': True, 'break_on_reject': True}
[ytdl-sub:yt-dlp] [generic] Extracting URL: https://pdodswr-a.akamaihd.net/swr/swr-fernsehen/im-suedwesten/999652.xl.mp4#__youtubedl_smuggle=...m0KOGm5z9ak%3D%22%7D
[ytdl-sub:yt-dlp] [generic] qV5gwzS7OIbq4X/w6OwNgejSGYTY93skm0KOGm5z9ak=: Downloading webpage
[ytdl-sub:yt-dlp] [info] qV5gwzS7OIbq4X/w6OwNgejSGYTY93skm0KOGm5z9ak=: Downloading 1 format(s): mp4
[ytdl-sub:yt-dlp] [info] There are no video thumbnails to download
[ytdl-sub:yt-dlp] [download] Destination: .ytdl-sub-working-directory/Handwerkskunst!/qV5gwzS7OIbq4X⧸w6OwNgejSGYTY93skm0KOGm5z9ak=.mp4
```
...
```
[ytdl-sub:yt-dlp] [Metadata] There isn't any metadata to add
[ytdl-sub] The following error occurred for the subscription Handwerkskunst!:
Traceback (most recent call last):
  File "venv/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 373, in exception_handling
    yield
  File "venv/lib/python3.10/site-packages/ytdl_sub/cli/entrypoint.py", line 113, in _download_subscriptions_from_yaml_files
    subscription.download(dry_run=dry_run)
  File "venv/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 360, in download
    return self._process_subscription(
  File "venv/lib/python3.10/site-packages/ytdl_sub/subscriptions/subscription_download.py", line 305, in _process_subscription
    entry = downloader.download(entry)
  File "venv/lib/python3.10/site-packages/ytdl_sub/downloaders/url/downloader.py", line 490, in download
    download_entry = self._extract_entry_info_with_retry(entry=entry)
  File "venv/lib/python3.10/site-packages/ytdl_sub/downloaders/url/downloader.py", line 338, in _extract_entry_info_with_retry
    download_entry_dict = YTDLP.extract_info_with_retry(
  File "venv/lib/python3.10/site-packages/ytdl_sub/downloaders/ytdlp.py", line 137, in extract_info_with_retry
    raise FileNotDownloadedException(
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-working-directory/Handwerkskunst!/%(id)s.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': '/usr/bin/ffmpeg', 'download_archive': '.ytdl-sub-working-directory/Handwerkskunst!/.ytdl-sub-Handwerkskunst!-download-archive.json', 'postprocessors': [{'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'break_on_existing': True, 'break_on_reject': True}, 'kwargs': {'url': 'https://pdodswr-a.akamaihd.net/swr/swr-fernsehen/im-suedwesten/999652.xl.mp4#__youtubedl_smuggle=%7B%22force_videoid%22%3A+%22qV5gwzS7OIbq4X%2Fw6OwNgejSGYTY93skm0KOGm5z9ak%3D%22%7D'}}
```

---

I suspect the issue is related to the reported destination `.ytdl-sub-working-directory/Handwerkskunst!/qV5gwzS7OIbq4X⧸w6OwNgejSGYTY93skm0KOGm5z9ak=.mp4` and the `/` between `X` and `w`. My impression is that `Entry.is_downloaded` does not receive a sanitized filename here and, thus, is unable detect the downloaded file which has `/` replaced by `_` in its filename.

Best regards
itd

**Comment by jmbannon** [comment]
Do you see in the yt-dlp logs somewhere that has a _ instead of / ?

**Comment by jmbannon** [comment]
The linked PR should hopefully fix the issue - going to close. Please re-open if the issue still persists
