### ISSUE TITLE
ERROR: Parse error at position 35 (near 'Style:\n::cue(c.color')

### ISSUE THREAD

**Issue by ST3FAN-DE** [jmbannon/ytdl-sub#918]
[2024-02-05-092723.error.log](https://github.com/jmbannon/ytdl-sub/files/14162422/2024-02-05-092723.error.log)
[config.yaml.txt](https://github.com/jmbannon/ytdl-sub/files/14162436/config.yaml.txt)
[subscriptions.yaml.txt](https://github.com/jmbannon/ytdl-sub/files/14162446/subscriptions.yaml.txt)

Config and Subcriptions is working for all of my channels and Playlists. But the Channel @Grian is the only one with this error.

[ytdl-sub:yt-dlp] ERROR: Parse error at position 35 (near 'Style:\n::cue(c.color')
[ytdl-sub] The following error occurred for the subscription Grian:
Traceback (most recent call last):
  File "ytdl_sub\subscriptions\subscription_download.py", line 375, in exception_handling
  File "ytdl_sub\cli\entrypoint.py", line 126, in _download_subscriptions_from_yaml_files
  File "ytdl_sub\subscriptions\subscription_download.py", line 362, in download
  File "ytdl_sub\subscriptions\subscription_download.py", line 306, in _process_subscription
  File "ytdl_sub\downloaders\url\downloader.py", line 498, in download
  File "ytdl_sub\downloaders\url\downloader.py", line 338, in _extract_entry_info_with_retry
  File "ytdl_sub\downloaders\ytdlp.py", line 137, in extract_info_with_retry
ytdl_sub.utils.exceptions.FileNotDownloadedException: yt-dlp failed to download an entry with these arguments: {'ytdl_options': {'ignoreerrors': True, 'outtmpl': '.ytdl-sub-working-directory\\Grian\\%(id)S.%(ext)s', 'writethumbnail': True, 'ffmpeg_location': 'ffmpeg.exe', 'download_archive': '.ytdl-sub-working-directory\\Grian\\.ytdl-sub-Grian-download-archive.json', 'max_downloads': 15, 'merge_output_format': 'mp4', 'postprocessors': [{'key': 'FFmpegVideoRemuxer', 'when': 'post_process', 'preferedformat': 'mp4'}, {'key': 'FFmpegEmbedSubtitle', 'already_have_subtitle': True}, {'key': 'SponsorBlock', 'when': 'pre_process', 'categories': ['outro', 'selfpromo', 'preview', 'interaction', 'sponsor', 'music_offtopic', 'intro']}, {'key': 'ModifyChapters'}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}, {'key': 'ModifyChapters', 'force_keyframes': False, 'remove_sponsor_segments': ['sponsor', 'selfpromo']}, {'key': 'FFmpegMetadata', 'add_chapters': True, 'add_metadata': False}], 'writesubtitles': True, 'writeautomaticsub': True, 'subtitleslangs': ['en', 'de'], 'format': 'bestvideo[height<=1440]+bestaudio/mp4', 'break_on_existing': True, 'extractor_args': {'youtube': {'lang': ['en']}}, 'break_on_reject': True}, 'kwargs': {'url': 'https://www.youtube.com/watch?v=CRlNu1rgJ4w'}}
[ytdl-sub] An uncaught error occurred:
NoneType: None
[ytdl-sub] Version 2024.01.15+c0ca3c3

**Comment by Svagtlys** [comment]
Looks like this error might have to do with the colored subtitles? https://github.com/yt-dlp/yt-dlp/issues/5158

You could try turning off subtitle pulling for this subscription if you have them turned on. https://ytdl-sub.readthedocs.io/en/latest/config_reference/plugins.html#subtitles

```
subtitles:
  embed_subtitles: False
```

**Comment by ST3FAN-DE** [comment]
Yes, of course it's a temp workaround. But it would be great, if it' s patched in the future. Or just Handle the exception, an skip subtitle for this specific video and proceed with the rest of the subscriptions videos...

**Comment by jmbannon** [comment]
How are you running ytdl-sub @ST3FAN-DE ? it could be a stale ffmpeg issue (though doubtful). The issue is happening within yt-dlp so it may be worth filing an issue there or searching their GH for a workaround
