### ISSUE TITLE
Can no longer download songs from mixed playlist

### ISSUE THREAD

**Issue by sweiggster51** [jmbannon/ytdl-sub#940]
I realized when my cron_job stopped downloading new songs that something went wrong with my presets. When trying to run, I get this:
"abc@a5bfba1b4c09:~/ytdl-sub-configs$ ytdl-sub sub subscriptions.yaml
[ytdl-sub] Validating subscriptions...
[ytdl-sub] Beginning subscription download for plex_music_playlist
[ytdl-sub] The following error occurred for the subscription plex_music_playlist:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 375, in exception_handling
    yield
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/cli/entrypoint.py", line 126, in _download_subscriptions_from_yaml_files
    subscription.download(dry_run=dry_run)
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/subscriptions/subscription_download.py", line 339, in download
    self._enhanced_download_archive.reinitialize(dry_run=dry_run)
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/ytdl_additions/enhanced_download_archive.py", line 442, in reinitialize
    self._download_mapping = self._maybe_load_download_mappings(
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/ytdl_additions/enhanced_download_archive.py", line 392, in _maybe_load_download_mappings
    return DownloadMappings.from_file(json_file_path=mapping_file_path)
  File "/usr/local/lib/python3.10/dist-packages/ytdl_sub/ytdl_additions/enhanced_download_archive.py", line 173, in from_file
    entry_mappings_json = json.load(json_file)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[ytdl-sub] 
No files changed for plex_music_playlist
[ytdl-sub] Download Summary:
plex_music_playlist     0 0 0     0 JSONDecodeError
Total: 1                0 0 0     0 Error

See `/tmp/ytdl-sub.errors88gs9ctd` for details on errors.
Consider making a GitHub issue including the uploaded log file.
abc@a5bfba1b4c09:~/ytdl-sub-configs$"

Config: https://pastebin.com/ZKHD9pT2
Subscriptions: https://pastebin.com/0s2SGJt6

**Comment by jmbannon** [comment]
Sorry for the delayed response, it seems your download archive file got corrupted and is no longer valid JSON.

You could try manually editing it to get it back to proper JSON format

**Comment by jmbannon** [comment]
Closing, since this issue I've added changes to better prevent corruption
